### PR TITLE
docs: Fix typo

### PR DESCRIPTION
**Pull request by hezhizhen**

### CODE REVIEW

**Comment by hezhizhen** [comment]
The changes in `go.sum` are automatically made by running `go mod tidy -v` with Go 1.18.

**Comment by hezhizhen** [comment]
> Thanks for this. Please could you remove the changes for `go.sum` as these extra entries are needed when cross-compiling. Also note that, although you can compile chezmoi with Go 1.18, the minimum supported version is Go 1.19, as this is the oldest version of Go that is still maintained.

Okay, but maybe it's better to update Go version in `go.mod` from 1.18 to 1.19?

**Comment by twpayne** [comment]
> Okay, but maybe it's better to update Go version in `go.mod` from 1.18 to 1.19?

Would you mind doing that in this PR? Also, please could you change the commit message to `docs: Fix typos`. Thank you :)

**Comment by hezhizhen** [comment]
> > Okay, but maybe it's better to update Go version in `go.mod` from 1.18 to 1.19?
> 
> Would you mind doing that in this PR? Also, please could you change the commit message to `docs: Fix typos`. Thank you :)

Done. How about PR title?

**Comment by twpayne** [comment]
Thank you very much! The commit message matters because it's used to generate the release notes. The PR title doesn't matter so much as it's not used anywhere else, but thank you for updating it.

**Pull request merged**
