### PR TITLE
:memo: Update docs so that oh-my-zsh tarball goes to TMPDIR instead of HOME

### PR DESCRIPTION
**Pull request by Anthonyive**

### CODE REVIEW

**Comment by twpayne** [comment]
Thank you for this. Would you mind squashing the commits into one and removing the emoji from the commit message?

**Comment by twpayne** [comment]
There's also a bit of trailing whitespace in `docs/HOWTO.md` that needs to be removed.

**Comment by Anthonyive** [comment]
@twpayne Sorry, this is my first time squash commits. Does it look good now?

**Comment by twpayne** [comment]
Ah, this is close but not quite right - the commit as it is at the moment undoes some recent changes in chezmoi. I think this is because the PR comes from your `master` branch rather than a separate branch containing just the changes.

Here are a few commands that should hopefully fix things:

```console
$ git fetch origin # get latest commits
$ git reset --hard origin/master # restore the state to chezmoi's master
$ git cherry-pick dbbf6a # add the commit containing just the changes we want
$ git push --force # update our master to contain only only the extra commit
```

I haven't tested the above, so it might not be exactly right.

For pull requests in the future, create a separate branch in git first (use `git branch`), add your changes to that branch, and then create the PR from that branch.

Happy to help further if you have questions or something doesn't work :)

**Comment by Anthonyive** [comment]
@twpayne I have to add this repo as a new remote to fetch. Anyway, does it look good now?

Here is the git log:

```bash
~/Downloads/chezmoi master ⇣2⇡8
❯ glols
─────┬─────────────────────────────────────────────────────────────────────────────────────────────────
     │ STDIN
─────┼─────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ * 33d433a - (HEAD -> master) Update docs so that oh-my-zsh tarball goes to TMPDIR instead of HOM
     │ E (4 seconds ago) <Tom Payne>
   2 │ |
   3 │ |  docs/HOWTO.md     | 16 ++++++++++------
   4 │ |  docs/REFERENCE.md |  4 ++--
   5 │ |  2 files changed, 12 insertions(+), 8 deletions(-)
   6 │ *   1cab01e - (upstream/master) Merge pull request #1271 from twpayne/fix-1269 (2 hours ago) <To
     │ m Payne>
   7 │ |\
   8 │ | * 31a5fb7 - Prioritize /etc/hosts over /etc/hostname for FQDN hostname (2 hours ago) <Tom Payn
     │ e>
   9 │ |/
  10 │ |
  11 │ |    internal/chezmoi/chezmoi_unix.go      | 4 ++--
  12 │ |    internal/chezmoi/chezmoi_unix_test.go | 8 ++++++++
  13 │ |    2 files changed, 10 insertions(+), 2 deletions(-)
  14 │ * 32d4a92 - Improve documentation of chezmoi edit (2 days ago) <Tom Payne>
  15 │ |
  16 │ |  docs/REFERENCE.md | 10 +++++++++-
  17 │ |  1 file changed, 9 insertions(+), 1 deletion(-)
  18 │ * ef49f6a - Tweak FAQ on chezmoi edit (2 days ago) <Tom Payne>
  19 │ |
  20 │ |  docs/FAQ.md | 57 +++++++++++++++++++++++++++++++++++++--------------------
  21 │ |  1 file changed, 37 insertions(+), 20 deletions(-)
  22 │ *   58570b5 - Merge pull request #1263 from twpayne/update-deps (8 days ago) <Tom Payne>
  23 │ |\
  24 │ | * af34a92 - Update golangci-lint to v1.41.0 (8 days ago) <Tom Payne>
  25 │ | |
  26 │ | |  .github/workflows/main.yml | 2 +-
```

**Comment by twpayne** [comment]
Yes, that's really close. There's just one thing: currently I'm credited as author and you as committer, whereas really this is all your work so we should fix the author credit. You can do this by checking out your `master` branch and running

```console
$ git commit --amend --author 'Your Name <your.email@domain.com>' --no-edit
$ git push --force
```

**Comment by twpayne** [comment]
Thank you @Anthonyive for your contribution and particularly your patience in getting this merged :)

**Comment by Anthonyive** [comment]
No worries! Thank you for your patience

**Pull request merged**
