### PR TITLE
feat: Add bitwardenSecrets template function

### LINKED ISSUE #3193: Integration of Bitwarden Secrets CLI into chezmoi
## Is your feature request related to a problem? Please describe.

`chezmoi` currently integrates with the regular `Bitwarden CLI`, but lacks support for the newer `Bitwarden Secrets CLI`.

## Describe the solution you'd like

Integrate Bitwarden Secrets CLI into chezmoi to allow direct pulling of secrets into managed dotfiles.

## Describe alternatives you've considered

Continue using the older CLI, missing out on features of the Secrets CLI.

## Additional context

The Bitwarden Secrets CLI is an emerging tool focusing on secrets management. Integrating it with chezmoi can enhance security and user experience. 

Documentation link: [Bitwarden Secrets Manager CLI](https://bitwarden.com/help/secrets-manager-cli/).

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #3193.

@fslef would you be able to test this?

### CODE REVIEW

**Comment by fslef** [comment]
> Fixes #3193.
> 
> @fslef would you be able to test this?

I would be glad to help. What is the best way to proceed? 
I'm running mac os and I've installed chezmoi using Homebrew

**Comment by twpayne** [comment]
The easiest way to proceed is to download the chezmoi binary built from this PR, which you can find [here](https://github.com/twpayne/chezmoi/actions/runs/5985414703#artifacts). I guess you'll want either the [chezmoi-darwin-amd64](https://github.com/twpayne/chezmoi/suites/15513000921/artifacts/885765497) or [chezmoi-darwin-arm64](https://github.com/twpayne/chezmoi/suites/15513000921/artifacts/885765499) depending on your architecture. Some unzipping might be needed.

You can then run this binary locally and use the `chezmoi execute-template` command to test the `bitwardenSecrets` template function, something like:

```console
$ export BWS_ACCESS_TOKEN=my-access-token
$ ./chezmoi execute-template '{{ bitwardenSecrets "my-secret-id" | toJson }}'
$ ./chezmoi execute-template '{{ (bitwardenSecrets "my-secret-id").value }}'
```

Also, does the `bitwardenSecrets` template function seem reasonable? I made the access token overridable for the case where people want to get secrets from different projects.

**Review by halostatue — APPROVED** [review]
I haven’t tried this (no bitwarden account), but the code is solid.

The only thing that seems to be missing is "profile" support, but I don’t see an easy way to do that with support for the access token as a parameter, since Go (templates) has no concept of a "named" parameter. https://bitwarden.com/help/secrets-manager-cli/#config-profile

**Comment by fslef** [comment]
Hello @twpayne, just confirming that it's working as expected.
Big thanks for the speedy implementation.

**Pull request merged**
