### PR TITLE
docs: Improved Bitwarden login documentation

### LINKED ISSUE #2953: Bitwarden Session One-liner not valid anymore
## Describe the bug

use Bitwarden Session One-liner to automate login and unlock and then rely on chezmoi runtime to handle filling secrets via `.tmpl` files 

## To reproduce

1. I do have `run_onchange_before_install-bw-cli.sh` which install bw cli and then execute `export BW_SESSION=$(bw {login,unlock} --raw)`
2. get error `Email address is invalid`
3. chezmoi exit with `error calling bitwarden: /path/to/bitwarden/bin/bw get item cf_api_key: exit status 1`

## Expected behavior

should proceed with filling templates file 

## Output of command with the `--verbose` flag

```console
Email address is invalid.
chezmoi: template: dot_zshrc.tmpl:19:4: executing " dot_zshrc.tmpl" at <bitwarden "item" "cf_api_key">: error calling bitwarden: /path/to/bitwarden/bin/bw get item cf_api_key: exit status 1
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.33.3, commit fe6010e8b2518ddabfcd5f58236763b4f2e90ff8, built at 2023-04-21T20:41:23Z, built by goreleaser
ok        latest-version       v2.33.3
ok        os-arch              linux/arm64 (Ubuntu 22.04 LTS (Jammy Jellyfish))
ok        uname                Linux ubuntu-linux-22-04-desktop 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 15:58:51 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
ok        go-version           go1.20.3 (gc)
ok        executable           /snap/chezmoi/663/chezmoi
ok        upgrade-method       snap-refresh
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2023-04-23T20:49:47+02:00
ok        source-dir           ~/.local/share/chezmoi is a git working tree (clean)
warning   suspicious-entries   ~/.local/share/chezmoi/home/.chezmoiexternal.tmpl
ok        working-tree         ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir             ~ is a directory
ok        umask                002
ok        cd-command           found /bin/bash
ok        cd-args              /bin/bash
info      diff-command         not set
ok        edit-command         found /usr/bin/vi
ok        edit-args            /usr/bin/vi
ok        git-command          found /usr/bin/git, version 2.34.1
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /bin/bash
ok        shell-args           /bin/bash
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.27
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found ~/.nvm/versions/node/v18.16.0/bin/bw, version 2023.3.0
info      dashlane-command     dcli not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      rbw-command          rbw not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set

```

</details>

## Additional context

- how can I automate login, unlock and set BW_SESSION using a similar approach to this one-liner method? Is there a way using chezmoi functions?

## Update doc
⚠️ since this approach is no longer valid – it will break chezmoi from completing init. Instead, user should have bitwarden installed and logged in and unlocked to proceed with chezmoi init
https://github.com/twpayne/chezmoi/blob/899338d4069cc4102cf7d18f658db222d8b64508/assets/chezmoi.io/docs/user-guide/password-managers/bitwarden.md?plain=1#L21-L27

### PR DESCRIPTION
**Pull request by halostatue**
Closes #2953

### CODE REVIEW

**Comment by halostatue** [comment]
This should be reviewed by Bitwarden users to verify before merging. Based on previous PRs, I think that @cawaltrip, @choznerol, and @benmezger are likely to have more familiarity with this, but the updates are based on the [Bitwarden CLI documentation](https://bitwarden.com/help/cli/#log-in) on `login`.

These folks may also be interested in the further thoughts I had on #2953 for multiple account support.

**Review by twpayne — APPROVED** [review]
Thanks - this looks great. I'm not a Bitwarden user so I'll defer to them for a proper review.

**Comment by julian-poidevin** [comment]
Hello, sorry in advance if my comment is unrelated to this PR.
Are you sure the `export BW_SESSION=$(bw unlock --raw)` command works every time ?

I'm using it in the following `run_before_01-login-password-manager.sh.tmpl` template script and it returns a `mac failed.` error message :

```sh
#!/bin/sh
{{ if .personal -}}
export BW_SESSION=$(bw unlock --raw)
{{ end -}}
```

**Comment by twpayne** [comment]
@julian-poidevin Please read [this detailed explanation](https://github.com/twpayne/chezmoi/issues/2953#issuecomment-1529067638) from @halostatue.




> I'm using it in the following `run_before_01-login-password-manager.sh.tmpl` template script and it returns a `mac failed.` error message :
> 
> ```shell
> #!/bin/sh
> {{ if .personal -}}
> export BW_SESSION=$(bw unlock --raw)
> {{ end -}}
> ```

This script cannot ever work because it sets an environment variable in a child process, which cannot be seen by the parent process. In this case, the child process is the `run_before_` script and the parent process is chezmoi. i.e, chezmoi cannot see the `BW_SESSION` environment variable set in your `run_before_` script.

**Comment by julian-poidevin** [comment]
Thanks a lot @twpayne for the link and @halostatue for the clear explanation. As I understand there is currently no workaround (apart from using `bw login` before `chezmoi apply`) to automatically log into `bw cli` using chezmoi scripts ?

**Comment by twpayne** [comment]
That is correct.

**Comment by halostatue** [comment]
> As I understand there is currently no workaround _(apart from using `export BW_SESSION=$(bw unlock --raw)` before `chezmoi apply`)_ to automatically log into `bw cli` using chezmoi scripts ?

Understand that neither @twpayne nor I are Bitwarden users, but *based on what I have read*, it looks like if you use [doy/rbw](https://github.com/doy/rbw) and the `rbw*` functions, the session can be established in-flight and will be persisted across the first execution. `rbw` is an unofficial CLI and apparently works differently *otherwise* than the official Bitwarden client, but there are other chezmoi users who use and have contributed the `rbw*` functions in the first place.

**Review by benmezger — APPROVED** [review]

**Comment by julian-poidevin** [comment]
> The documentation looks good to me.
> 
> > As I understand there is currently no workaround (apart from using export BW_SESSION=$(bw unlock --raw) before chezmoi apply) to automatically log into bw cli using chezmoi scripts ?
> 
> Correct, the token lives for a few days, then you must unlock it again. There is a small hack that I do: I unlock and export the token, then I apply Chezmoi. In my zsh configuration, I have the [following](https://github.com/benmezger/dotfiles/blob/b823aad4749302ddae7fd8b0ca55b2fe9cf11e3a/dot_env-secrets.tmpl#L7) Chezmoi template, and I include it [here](https://github.com/benmezger/dotfiles/blob/b823aad4749302ddae7fd8b0ca55b2fe9cf11e3a/dot_zsh/exports.zsh#L61). This will take the exported token and put it in there, so the next time I run Chezmoi, it will re-use that token. So I use Chezmoi to automatically take that exported token and put it in my config, and this happens every time I need to unlock and export a new token, so I will always have the latest token in my zsh config.

Thanks for the tip @benmezger ! Works great ! 👍🏻 🎉

**Comment by halostatue** [comment]
Thanks for the feedback @benmezger! I’m going to merge this now.

**Pull request merged**
