### PR TITLE
Document that fish completion exists in REFERENCE.md

### PR DESCRIPTION
**Pull request by markstos**
Also go ahead and provide an example of what do with the output.

The example shows writing the completion code to a file where fish will automatically load it from.

Supercedes #340.

### CODE REVIEW

**Comment by twpayne** [comment]
You'll need to run `make generate` to update `helps.gen.go` too.

**Comment by markstos** [comment]
Ah, I'll let another contributor pick up that piece. I don't have a Go dev environment setup currently.

**Comment by twpayne** [comment]
OK, no worries. I'll create a new PR with you credited as author.

**Comment by twpayne** [comment]
Closed with #346 with your author credit. Thank you again for your contribution :)

**Pull request closed without merging**
