### PR TITLE
feat: Improve configurability of automatic git commit messages

### PR DESCRIPTION
**Pull request by twpayne**
Refs #3321.

### CODE REVIEW

**Review by halostatue — APPROVED** [review]

**Comment by halostatue** [comment]
Looks good.

It would be nice if either of these options provided the template for `chezmoi git commit` to override the `commit-message` configuration, but that's a feature request.

**Review by halostatue — APPROVED** [review]

**Comment by twpayne** [comment]
Thanks for review @halostatue!

> It would be nice if either of these options provided the template for `chezmoi git commit` to override the `commit-message` configuration, but that's a feature request.

Currently `chezmoi git` passes all following arguments directly through to `git`. Adding special behavior for `chezmoi git commit` would require chezmoi to parse git arguments exactly as git does, which is a very slippery slope. However, this is a great idea so I've added `chezmoi generate git-commit-message` to generate the git commit message so you can do:

```console
$ chezmoi git commit -m "$(chezmoi generate git-commit-message)"
```

**Comment by halostatue** [comment]
Yeah. I thought that was a very clever way to do this and think it's appropriate.

**Comment by lgersman** [comment]
> Thanks for review @halostatue!
> 
> > It would be nice if either of these options provided the template for `chezmoi git commit` to override the `commit-message` configuration, but that's a feature request.
> 
> Currently `chezmoi git` passes all following arguments directly through to `git`. Adding special behavior for `chezmoi git commit` would require chezmoi to parse git arguments exactly as git does, which is a very slippery slope. However, this is a great idea so I've added `chezmoi generate git-commit-message` to generate the git commit message so you can do:
> 
> ```
> $ chezmoi git commit -m "$(chezmoi generate git-commit-message)"
> ```

Looks good for me ❤️. 

BTW: Can I also provide a individual commit message when chezmoi autoCommit/autoPush is enabled ? 

```
[git]
  autoPush = true
  autoCommit = true
```

When I do a `chezmoi re-add` commit and push is done automagically by chezmoi in this case.

**Comment by twpayne** [comment]
> BTW: Can I also provide a individual commit message when chezmoi autoCommit/autoPush is enabled ?

Yes. Use the `git.commitMessageTemplate` or `git.commitMessageTemplateFile` configuration variables to achieve this.

**Comment by lgersman** [comment]
No, I mean not the template but an individual commit message. 

Lets say i have changed a file and want the commit message *not* generated from the `git.commitMessageTemplateFile` but individual for exactly this change. 

But with configured autoCommit  it's not possible to provide a individual commit message, is'nt it ?

**Comment by twpayne** [comment]
You can use the `promptString` template function in your commit message template.

**Pull request merged**
