### PR TITLE
Only check minimum version in non-snapshot builds

### PR DESCRIPTION
**Pull request by twpayne**
@JustinGrote what do you think of this approach?

### CODE REVIEW

**Comment by JustinGrote** [comment]
I'll test the binary to see if it works, but I think even with a snapshot build its still technically a semver because it has a tag. And tagged semvers are considered less than the "release" version with no tags which is why the state check isn't working.

**Comment by twpayne** [comment]
Note that this the failure observed:

    chezmoi: source state requires version 0.0.0 or later, chezmoi is version 0.0.0-SNAPSHOT-3bc8688

is chezmoi's own internal version check (https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoiversion).

**Comment by JustinGrote** [comment]
Tested as working on windows, LGTM.
image

**Comment by twpayne** [comment]
The latest commit in this PR is `b275e0a740a3e9c07dbdedd2416c6bb774cbe984`. The version printed in your output begins with `5745fa3`. Are you sure you're testing the correct version?

**Comment by JustinGrote** [comment]
Yep, it's the merge of your PR and master done by the checkout action:
https://github.com/twpayne/chezmoi/pull/1014/checks?check_run_id=1764455798#step:5:462

**Comment by twpayne** [comment]
Thanks for the testing @JustinGrote. I missed that the version number `0.0.0-SNAPSHOT-hex` would have non-zero metadata and so was not equal to the zero [semver.Version](https://pkg.go.dev/github.com/coreos/go-semver/semver#Version) value. This is fixed now. Thank you for testing and please do report further problems!

**Pull request merged**
