### PR TITLE
Add KeePassXC support

### PR DESCRIPTION
**Pull request by twpayne**

### CODE REVIEW

**Comment by twpayne** [comment]
Fixes #22. @franek are you able to test this? See the changes to the documentation for how to use it.

**Comment by twpayne** [comment]
A key assumption in this PR is that each user only has a single KeePassXC database file. I think this is reasonable, but please tell me if the assumption is incorrect.

**Comment by twpayne** [comment]
@droidmonkey, CC'ing you out-of-the blue on this as you're a current major active developer of KeePassXC. Would appreciate any input you have on KeePassXC/chezmoi integration.

**Comment by droidmonkey** [comment]
Cool! I think for the purposes of chezmoi a single database assumption is fine. Any secrets needed would be in that database.

**Comment by twpayne** [comment]
Many thanks @droidmonkey 👍

**Pull request merged**
