### PR TITLE
fix: More reliable arch detection in install.ps1

### LINKED ISSUE #4127: PowerShell installation script `install.ps1` cannot download archive
## Describe the bug

Executing the PowerShell installation script will result in a 404 error message caused by the missing target architecture.

## To reproduce

Execute `iex "&{$(irm 'https://get.chezmoi.io/ps1')} -d"`:

```console
> iex "&{$(irm 'https://get.chezmoi.io/ps1')} -d"
DEBUG: BinDir: C:\Users\WDAGUtilityAccount\bin
DEBUG: Tag: latest
DEBUG: ChezmoiArgs:
DEBUG: tempDir: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\d72654bc-78b4-4fe2-a861-1fd5753ae790
DEBUG: goOS: windows
DEBUG: goArch:
DEBUG: checking GitHub for tag latest
DEBUG: found tag v2.55.0 for latest
found version 2.55.0 for latest/windows/
DEBUG: binarySuffix: .exe
DEBUG: archiveFormat: zip
DEBUG: goOSExtra:
DEBUG: archiveFilename: chezmoi_2.55.0_windows_.zip
DEBUG: tempArchivePath:
C:\Users\WDAGUtilityAccount\AppData\Local\Temp\d72654bc-78b4-4fe2-a861-1fd5753ae790\chezmoi_2.55.0_windows_.zip
DEBUG: downloading https://github.com/twpayne/chezmoi/releases/download/v2.55.0/chezmoi_2.55.0_windows_.zip
DEBUG: removing C:\Users\WDAGUtilityAccount\AppData\Local\Temp\d72654bc-78b4-4fe2-a861-1fd5753ae790
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:1 char:1
+ &{<#
+ ~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

```

## Expected behavior

chezmoi to be installed without any issues.

## Output of command with the `--verbose` flag

Not relevant.

## Output of `chezmoi doctor`

Not relevant.

## Additional context

The script tries to download the archive at `https://github.com/twpayne/chezmoi/releases/download/v2.55.0/chezmoi_2.55.0_windows_.zip`, which fails.

The architecture should be set, in my case, `amd64`. Then the download URL becomes `https://github.com/twpayne/chezmoi/releases/download/v2.55.0/chezmoi_2.55.0_windows_amd64.zip`, which is correct.

### PR DESCRIPTION
**Pull request by KapJI**
Value returned by `(Get-CimInstance -Class Win32_OperatingSystem).OSArchitecture` is locale dependant.

This version should work the same for any locale. And it works both in powershell.exe and pwsh.exe.

Fixes #4127

### CODE REVIEW

**Review by bradenhilton — APPROVED** [review]
I'm happy if @nagromc is happy.

Also, I noticed that some jobs from `main` are running when they shouldn't be. I think the conditional needs to be moved up to the job level instead of the step level.

**Comment by KapJI** [comment]
I'm going to add a bit more of error handling, please do not merge it yet.

**Comment by KapJI** [comment]
> I'm going to add a bit more of error handling, please do not merge it yet.

Done.

> I noticed that some jobs from main are running when they shouldn't be.

I think this is expected. There are some spellcheckers and `test-ubuntu` is configured to run for all changes just in case.

**Comment by bradenhilton** [comment]
> I think this is expected. There are some spellcheckers and `test-ubuntu` is configured to run for all changes just in case.

Testing chezmoi shouldn't be necessary when only the install scripts are changed. That was the reason why I separated them in the first place (granted, that was more of an issue before you sped up the test jobs, as the entire workflow used to run for any change).

**Comment by twpayne** [comment]
Thank you for the fast fix @KapJI and review @bradenhilton!

**Pull request merged**
