### PR TITLE
feat: Add Illumos support

### PR DESCRIPTION
**Pull request by twpayne**
cc @bardo. This isn't working yet.

### CODE REVIEW

**Comment by twpayne** [comment]
cc @torculus

**Comment by torculus** [comment]
So, in testdata/scripts/scriptsubdir_unix.txt, it looks like `chezmoi apply --force` isn't creating the subdirectories in $WORK
Unfortunately, I can't find out where `chezmoi apply` is implemented

Also, in https://github.com/twpayne/chezmoi/blob/a390a6f7fe0444341125ad6f2b854fb31237c7c8/assets/vagrant/openindiana.Vagrantfile#L6 , you may want to include [`SUNWcs`](http://pkg.openindiana.org/hipster/info/0/SUNWcs%400.5.11%2C5.11-2020.0.1.20740%3A20211021T012643Z) and `archiver/gnu-tar` to avoid hiccups down the road

**Comment by torculus** [comment]
Just figured you might want to hear that `chezmoi` has officially been packaged in OpenIndiana's [repos](http://pkg.openindiana.org/hipster/info/0/application%2Fchezmoi%402.7.3%2C5.11-2020.0.1.0%3A20211030T190707Z)

**Comment by twpayne** [comment]
That's brilliant, thank you! Would you like to open a PR to https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md#one-line-package-install to add the install instructions for OpenIndiana?

**Comment by twpayne** [comment]
@torculus thank you so much for this. I added the install docs for OpenIndiana in #1580.

When testing I noticed that `chezmoi doctor` as installed by `pkg install application/chezmoi` reports that chezmoi's version is dev:

```
$ uname -a
SunOS openindiana 5.11 illumos-79a6379db8 i86pc i386 i86pc
$ pfexec pkg install application/chezmoi
           Packages to install:  1
       Create boot environment: No
Create backup boot environment: No

DOWNLOAD                                PKGS         FILES    XFER (MB)   SPEED
Completed                                1/1           2/2    12.0/12.0 14.3M/s

PHASE                                          ITEMS
Installing new actions                         15/15
Updating package state database                 Done
Updating package cache                           0/0
Updating image state                            Done
Creating fast lookup database                   Done
$  chezmoi --version
chezmoi version dev
```

Would you mind setting chezmoi's embedded version to the version of chezmoi (2.7.3 in this case)? Instructions on how to do this are [here](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#packaging). Please let me know how I can help. I did try to find the OpenIndiana package sources repo to submit a patch directly, but my initial attempts to find the source repo were unsuccessful.

**Comment by torculus** [comment]
Yeah, I can definitely look into embedding the metadata. I left it out in the package because it rendered the binary unusable after going through OI's build process. Speaking of which, you can find the git repo [here](https://github.com/OpenIndiana/oi-userland) and the documentation [here](http://docs.openindiana.org/dev/userland/). Since all packaging requests are manually-reviewed, I didn't think that would be something you could quickly spin up in a VM

**Comment by torculus** [comment]
So, I managed to create a usable binary for version 2.7.5 with most of the metadata (including `main.version`, `main.date`, and `main.builtBy`). I submitted that to oi-userland with [this](https://github.com/OpenIndiana/oi-userland/pull/7269) pull request. I verified that `chezmoi --version` works with this one. Hopefully it should be merged in the next few days

**Comment by twpayne** [comment]
Awesome, thank you very much!

**Comment by Toasterson** [comment]
@twpayne As we are all still talking in this PR I assume it's OK to answer here about the version number embedding? 

If not I'll gladly open a new Issue.
I am one of the Maintainers of OpenIndiana. The root problem about the version number embedding is, that our build system downloads a Release tarball from GitHub. Your Makefile is not made for that usecase and thus fails to load the Version number correctly. It's a bit odd for my why other packaging maintainers have not opened an issue yet, as I am sure debian has at least in the past had a policy about not using git as build source and for many applications with autotools one must use the release tarballs and not the source repo. Our build system still expects this more autotools and vcs independant behaviour. Thus chezmoi cannot build unless we hardcode the version number into the makefile with a patch.

See #openindiana/7269 for the patch and discussion.

**Comment by twpayne** [comment]
@Toasterson thank you for all this info. Please could you open a new issue so this doesn't get lost. I'm keen to help here :)

**Comment by twpayne** [comment]
Background info: https://github.com/twpayne/chezmoi/issues/1576 and https://github.com/goreleaser/goreleaser/pull/2620 are also relevant.

**Comment by Toasterson** [comment]
@twpayne opened #1610

**Pull request merged**
