### PR TITLE
feat: Add git-archive external type

### LINKED ISSUE #1623: Add a `git-archive` external type that respects `.gitignore` files
## Is your feature request related to a problem? Please describe.

As proposed by @felipecrs in [this comment](https://github.com/twpayne/chezmoi/issues/1421#issuecomment-964473844) in #1421, importing archives generated by git should respect `.gitignore` files.

## Describe the solution you'd like

Described perfectly by @felipecrs in https://github.com/twpayne/chezmoi/issues/1421#issuecomment-964473844.

## Describe alternatives you've considered

n/a

## Additional context

n/a

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #1623.

@felipecrs could you test this to check that it matches what you had in mind?

### CODE REVIEW

**Comment by felipecrs** [comment]
@twpayne this is amazing!! I'm super excited to test, but I'm traveling at the moment.

If you don't mind, I can provide feedback for on Monday.

**Comment by twpayne** [comment]
No rush at all! Please only test at your convenience, and enjoy your travels :)

**Comment by felipecrs** [comment]
I shall test it soon.

**Comment by felipecrs** [comment]
@twpayne I did [this in my dotfiles](https://github.com/felipecrs/dotfiles/pull/50/files) and this is what is happening now:

```console
❯ ~/chezmoi apply --force
chezmoi: .oh-my-zsh: https://github.com/ohmyzsh/ohmyzsh/archive/5b987e59d0fce1a74bcfd51750c6f52d7c29c647.tar.gz: skip this directory

❯ /mnt/c/Users/felip/Downloads/chezmoi apply --force --verbose --debug
2021-12-07T16:21:29-03:00 INF persistentPreRunRootE args=[] goVersion=go1.17.4 version={"builtBy":"goreleaser","commit":"f10444a51f3e184c2ccc6e20ea9c89111845de0b","date":"2021-12-05T16:10:22Z","version":"2.9.2-SNAPSHOT-f10444a5"}
2021-12-07T16:21:29-03:00 INF Stat component=system name=/home/felipecrs/.config/chezmoi/chezmoistate.boltdb
2021-12-07T16:21:29-03:00 INF Stat component=system name=/home/felipecrs/.dotfiles/.git
2021-12-07T16:21:29-03:00 INF ReadFile component=system data="home\n" name=/home/felipecrs/.dotfiles/.chezmoiroot
2021-12-07T16:21:29-03:00 ERR ReadFile error="open /home/felipecrs/.dotfiles/home/.chezmoi.json.tmpl: no such file or directory" component=system data= name=/home/felipecrs/.dotfiles/home/.chezmoi.json.tmpl
2021-12-07T16:21:29-03:00 ERR ReadFile error="open /home/felipecrs/.dotfiles/home/.chezmoi.toml.tmpl: no such file or directory" component=system data= name=/home/felipecrs/.dotfiles/home/.chezmoi.toml.tmpl
2021-12-07T16:21:29-03:00 INF ReadFile component=system data="{{- /* The following variables are only available within this fi..." name=/home/felipecrs/.dotfiles/home/.chezmoi.yaml.tmpl
2021-12-07T16:21:29-03:00 ERR Mkdir error="mkdir /home/felipecrs/.config/chezmoi: file exists" component=system name=/home/felipecrs/.config/chezmoi perm=511
2021-12-07T16:21:29-03:00 INF Stat component=system name=/home/felipecrs/.config/chezmoi
2021-12-07T16:21:29-03:00 INF Get bucket=configState component=persistentState key=configState value="{\"configTemplateContentsSHA256\":\"f4c42ce0b16356dd56ee01d2ed27795cbea5b4cdc36cea007e27cb1c66b916fe\"}"
2021-12-07T16:21:29-03:00 ERR ReadFile error="open /home/felipecrs/.dotfiles/.chezmoiversion: no such file or directory" component=system data= name=/home/felipecrs/.dotfiles/.chezmoiversion
2021-12-07T16:21:29-03:00 INF ReadFile component=system data="home\n" name=/home/felipecrs/.dotfiles/.chezmoiroot
2021-12-07T16:21:29-03:00 INF Stat component=system name=/home/felipecrs/.dotfiles/home
2021-12-07T16:21:29-03:00 INF Stat component=system name=/home/felipecrs/.dotfiles/home
2021-12-07T16:21:29-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home
2021-12-07T16:21:29-03:00 INF ReadFile component=system data="2.9.1\n" name=/home/felipecrs/.dotfiles/home/.chezmoiversion
2021-12-07T16:21:29-03:00 INF ReadFile component=system data="{{- define \"getGithubHeadRevision\" -}}\n{{-   $repo := get . \"rep..." name=/home/felipecrs/.dotfiles/home/.chezmoiexternal.yaml
2021-12-07T16:21:29-03:00 INF ReadFile component=system data="NAME=\"Ubuntu\"\nVERSION=\"20.04.3 LTS (Focal Fossa)\"\nID=ubuntu\nID_L..." name=/etc/os-release
2021-12-07T16:21:29-03:00 INF Output args=["git","ls-remote","https://github.com/ohmyzsh/ohmyzsh.git","HEAD"] output="5b987e59d0fce1a74bcfd51750c6f52d7c29c647\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:29-03:00 INF IdempotentCmdOutput args=["git","ls-remote","https://github.com/ohmyzsh/ohmyzsh.git","HEAD"] component=system output="5b987e59d0fce1a74bcfd51750c6f52d7c29c647\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:30-03:00 INF Output args=["git","ls-remote","https://github.com/romkatv/powerlevel10k.git","HEAD"] output="3380f7503e7dc252163d5b30475335ed67f58a98\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:30-03:00 INF IdempotentCmdOutput args=["git","ls-remote","https://github.com/romkatv/powerlevel10k.git","HEAD"] component=system output="3380f7503e7dc252163d5b30475335ed67f58a98\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:30-03:00 INF Output args=["git","ls-remote","https://github.com/zsh-users/zsh-syntax-highlighting.git","HEAD"] output="c7caf57ca805abd54f11f756fda6395dd4187f8a\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:30-03:00 INF IdempotentCmdOutput args=["git","ls-remote","https://github.com/zsh-users/zsh-syntax-highlighting.git","HEAD"] component=system output="c7caf57ca805abd54f11f756fda6395dd4187f8a\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:31-03:00 INF Output args=["git","ls-remote","https://github.com/zsh-users/zsh-autosuggestions.git","HEAD"] output="a411ef3e0992d4839f0732ebeb9823024afaaaa8\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:31-03:00 INF IdempotentCmdOutput args=["git","ls-remote","https://github.com/zsh-users/zsh-autosuggestions.git","HEAD"] component=system output="a411ef3e0992d4839f0732ebeb9823024afaaaa8\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:32-03:00 INF Output args=["git","ls-remote","https://github.com/zsh-users/zsh-completions.git","HEAD"] output="1a0808696c5dd6d90ed530e512f3d0a28a7565b8\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:32-03:00 INF IdempotentCmdOutput args=["git","ls-remote","https://github.com/zsh-users/zsh-completions.git","HEAD"] component=system output="1a0808696c5dd6d90ed530e512f3d0a28a7565b8\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:32-03:00 INF Output args=["curl","-fsSL","-o","/dev/null","-w","%{url_effective}","https://github.com/denoland/deno/releases/latest"] output=https://github.com/denoland/deno/releases/tag/v1.16.4 path=/usr/bin/curl
2021-12-07T16:21:32-03:00 INF IdempotentCmdOutput args=["curl","-fsSL","-o","/dev/null","-w","%{url_effective}","https://github.com/denoland/deno/releases/latest"] component=system output=https://github.com/denoland/deno/releases/tag/v1.16.4 path=/usr/bin/curl
2021-12-07T16:21:33-03:00 INF Output args=["curl","-fsSL","-o","/dev/null","-w","%{url_effective}","https://github.com/volta-cli/volta/releases/latest"] output=https://github.com/volta-cli/volta/releases/tag/v1.0.5 path=/usr/bin/curl
2021-12-07T16:21:33-03:00 INF IdempotentCmdOutput args=["curl","-fsSL","-o","/dev/null","-w","%{url_effective}","https://github.com/volta-cli/volta/releases/latest"] component=system output=https://github.com/volta-cli/volta/releases/tag/v1.0.5 path=/usr/bin/curl
2021-12-07T16:21:34-03:00 INF Output args=["curl","-fsSL","-o","/dev/null","-w","%{url_effective}","https://github.com/docker/compose/releases/latest"] output=https://github.com/docker/compose/releases/tag/v2.2.2 path=/usr/bin/curl
2021-12-07T16:21:34-03:00 INF IdempotentCmdOutput args=["curl","-fsSL","-o","/dev/null","-w","%{url_effective}","https://github.com/docker/compose/releases/latest"] component=system output=https://github.com/docker/compose/releases/tag/v2.2.2 path=/usr/bin/curl
2021-12-07T16:21:35-03:00 INF Output args=["curl","-fsSL","-o","/dev/null","-w","%{url_effective}","https://github.com/docker/buildx/releases/latest"] output=https://github.com/docker/buildx/releases/tag/v0.7.1 path=/usr/bin/curl
2021-12-07T16:21:35-03:00 INF IdempotentCmdOutput args=["curl","-fsSL","-o","/dev/null","-w","%{url_effective}","https://github.com/docker/buildx/releases/latest"] component=system output=https://github.com/docker/buildx/releases/tag/v0.7.1 path=/usr/bin/curl
2021-12-07T16:21:35-03:00 INF Output args=["git","ls-remote","https://github.com/ryanoasis/nerd-fonts.git","HEAD"] output="dc0256b92910edfaa20ecd78a9eaecaf929e4e9a\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:35-03:00 INF IdempotentCmdOutput args=["git","ls-remote","https://github.com/ryanoasis/nerd-fonts.git","HEAD"] component=system output="dc0256b92910edfaa20ecd78a9eaecaf929e4e9a\tHEAD\n" path=/usr/bin/git
2021-12-07T16:21:35-03:00 INF ReadFile component=system data="{{ if .is_devcontainer -}}\n.local/bin/code\n{{- end}}\n" name=/home/felipecrs/.dotfiles/home/.chezmoiignore
2021-12-07T16:21:35-03:00 INF ReadFile component=system data="{{ if not .is_devcontainer -}}\n\n*.deb\n*.rpm\n*.tar\n*.tar.gz\n*.tar..." name=/home/felipecrs/.dotfiles/home/.chezmoiremove
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_docker
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_local
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_local/bin
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_local/share
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_local/share/fonts
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_oh-my-zsh
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_oh-my-zsh/custom
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_oh-my-zsh/custom/plugins
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_oh-my-zsh/custom/plugins/exact_my-completions
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_sdkman
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_sdkman/etc
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_volta
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/dot_volta/bin
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/private_dot_kube
2021-12-07T16:21:35-03:00 INF ReadDir component=system name=/home/felipecrs/.dotfiles/home/repos
2021-12-07T16:21:35-03:00 INF ReadFile component=system data="\x1f�\b\x00\x00\x00\x00\x00\x00�<��\x12���D�夼wq;\x19�\x0e\x1b�pwg~~�\x063�tܫ����9����?�q,�_\x10�ۣ9�\u007f..." name=/home/felipecrs/.cache/chezmoi/external/517bd9369a0dfac4ead878850fce9c7bd7c9a355c93f0c31cb39fb8ba6c7967f.json.gz
chezmoi: .oh-my-zsh: https://github.com/ohmyzsh/ohmyzsh/archive/5b987e59d0fce1a74bcfd51750c6f52d7c29c647.tar.gz: skip this directory
```

**Comment by felipecrs** [comment]
Perhaps the .gitignore is being taken into account during the whole chezmoiexternal execution, while I think it should only be taken into account when expanding the tarball from where it was from.

**Comment by twpayne** [comment]
Thank you for the testing! The bug here was that chezmoi was not skipping ignored directories correctly. I've pushed a commit that should fix this. Could you test this PR again?

**Comment by felipecrs** [comment]
That issue is gone. But now, there is still one issue:

```
❯ /mnt/c/Users/felip/Downloads/chezmoi apply --force
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh.zwc
deleted file mode 100444
index db542bc522bd229568394ed028edd591d4217a79..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh.zwc and /dev/null differ
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install.zwc
deleted file mode 100444
index 8bc54271f029e91106ed17ec138a35e5ac021b98..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install.zwc and /dev/null differ
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/internal/configure.zsh.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/internal/configure.zsh.zwc
deleted file mode 100444
index 65ac2b0781a31d107eeef43664459ec7b0c1c9a7..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/internal/configure.zsh.zwc and /dev/null differ
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/internal/icons.zsh.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/internal/icons.zsh.zwc
deleted file mode 100444
index 01d12f0bc928dfc4ffa94b633e478417a26e961f..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/internal/icons.zsh.zwc and /dev/null differ
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh.zwc
deleted file mode 100444
index d683d1e09850682b2d376142d6bc9d893c992fff..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh.zwc and /dev/null differ
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/internal/parser.zsh.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/internal/parser.zsh.zwc
deleted file mode 100444
index 8603154101a93f7841fa9eeee5c741bbf8a27ccc..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/internal/parser.zsh.zwc and /dev/null differ
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/internal/worker.zsh.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/internal/worker.zsh.zwc
deleted file mode 100444
index 8d9f13d49b2d7e55aee8e2fde1094ccc3602c11c..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/internal/worker.zsh.zwc and /dev/null differ
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme.zwc
deleted file mode 100444
index 04b5a6332ceb40b3ccb42ea21c98bc61df0d8943..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme.zwc and /dev/null differ
diff --git a/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel9k.zsh-theme.zwc b/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel9k.zsh-theme.zwc
deleted file mode 100444
index 262ae9f42baa5dde43b549355b25d70596d3c8aa..0000000000000000000000000000000000000000
Binary files a/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel9k.zsh-theme.zwc and /dev/null differ
```

Such files are ignored in: 

```
❯ cat ~/.oh-my-zsh/custom/themes/powerlevel10k/.gitignore
*.zwc
```

**Comment by felipecrs** [comment]
Oh, and I would also suggest to update the existing examples which involve OMZ and related stuff to use `git-archive` instead of `archive` as well.

**Comment by twpayne** [comment]
Thanks for the testing! PR updated. Please take (another) look.

> Perhaps the .gitignore is being taken into account during the whole chezmoiexternal execution, while I think it should only be taken into account when expanding the tarball from where it was from.

Actually, it's the opposite: `.gitignore` files need to be taken into account during the whole chezmoi execution. Taking it into account when expanding the tarball has no effect as git will not include ignored files in the archive.

**Comment by felipecrs** [comment]
Awesome, that issue is now solved. Now, when I enable `exact: true` for OMZ, I run into:

```console
❯ ./chezmoi apply --force
chezmoi: .oh-my-zsh: inconsistent state (dot_oh-my-zsh, https://github.com/ohmyzsh/ohmyzsh/archive/5b987e59d0fce1a74bcfd51750c6f52d7c29c647.tar.gz); .oh-my-zsh/custom: inconsistent state (dot_oh-my-zsh/custom, https://github.com/ohmyzsh/ohmyzsh/archive/5b987e59d0fce1a74bcfd51750c6f52d7c29c647.tar.gz); .oh-my-zsh/custom/plugins: inconsistent state (dot_oh-my-zsh/custom/plugins, https://github.com/ohmyzsh/ohmyzsh/archive/5b987e59d0fce1a74bcfd51750c6f52d7c29c647.tar.gz)
```

But I wonder if that should really happen, as `.oh-my-zsh/custom` is in OMZ's `.gitignore`.

**Comment by felipecrs** [comment]
I think that what's happening here is that the `.gitignore`'s found inside of OMZ archive should be effective only during its analysis and expansion. For example: when expanding the OMZ archive, it should not care about files inside `.oh-my-zsh/custom`. When the next git-archive, all the rules from OMZ should be dropped, and then, the rules from P10K should be read and similarly only be effective during its analysis/expansion, so that the `*.zwc` can be ignored as well.

> For bonus points, if a parent directory has a .gitignore file containing .gitignore (yes, that's saying ignore all .gitignore files in subdirectories), should .gitignore files in externals in subdirectories be read or not?

I guess that's a question for git: https://stackoverflow.com/a/10176918/12156188. And looking at that, it seems to be possible. So ideally it should be respected.

**Comment by felipecrs** [comment]
So, I believe my comment above address your concerns about the _fundamental problems_, i.e., it's not about which files should be ignored (we should do whatever git do, period), but about at which point which `.gitignore`s will be effective.

The `.gitignore`s from OMZ archive should not be taken into account when performing the P10K analysis/expansion.

**Comment by jack1142** [comment]
Will this work with private Git repositories (through Authorization header or Basic Auth)?

**Comment by twpayne** [comment]
> Will this work with private Git repositories (through Authorization header or Basic Auth)? If this is out of scope for this, I can make a new issue.

No. Please make a new issue.

**Pull request closed without merging**
