### PR TITLE
Add stdinIsATTY template function

### LINKED ISSUE #1109: New template function: isatty
## Is your feature request related to a problem? Please describe.

When I have to install my dotfiles in a non-interactive way, such as in Codespaces, I have to rely on some environment variables (such as `CODESPACES=true`) to selectively enable input or not.

## Solution

A template function such as `isatty`, which would return `true` if the current session is interactive and therefore, I can proceed to ask for inputs. E.g. https://nodejs.org/api/tty.html#tty_tty_isatty_fd

## Alternatives

As said, for Codespaces I have the `CODESPACES` env var. For Remote - Containers, I also have a similar environment variable. For other cases, it's not well know. I could also check some environment variables which tells about TTY itself, but it would not be portable across Windows I guess.

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #1109.

@felipecrs would you be able to test this? I'm not sure how it behaves on Windows.

### CODE REVIEW

**Comment by felipecrs** [comment]
Sure, let me try.

**Comment by felipecrs** [comment]
Hm, I'm trying with the artifact generated...

```sh-session
➜ .\chezmoi.exe --version
chezmoi version v2.0.4-SNAPSHOT-5648577, commit 56485778b5334f3aa05b5d12abff0db00cc8cb2b, built at 2021-03-28T18:30:09Z, built by goreleaser
➜ .\chezmoi.exe execute-template '{{ stdinIsATTY }}'
chezmoi: template: arg1:1: function "stdinIsATTY" not defined
```

**Comment by twpayne** [comment]
Ah, you need the `--init` flag to `chezmoi execute-template` because `stdinIsATTY` is only available for generating the initial config file.

**Comment by felipecrs** [comment]
I realized it, sorry. I'm trying to figure out what to do to not have a stdin, to check.

**Comment by felipecrs** [comment]
Well, it doesn't work in the following scenario:

```sh-session
$ docker run -v c:\Users\felip\Downloads:c:\Downloads mcr.microsoft.com/windows:20H2 powershell.exe -Command "C:\Downloads\chezmoi.exe execute-template --init '{{ stdinIsATTY }}'"
true
```

**Comment by felipecrs** [comment]
But surprisingly, it works like a charm when using a `chezmoi init`. See:

```sh-session
> cat .\.chezmoi.toml.tmpl
{{ $email := "" }}
{{ if stdinIsATTY }}
{{   $email = promptString "email" }}
{{ else }}
{{   $email = "user@example.com" }}
{{ end }}

[data]
    email = "{{ $email }}"
> docker run -v c:\Users\felip\Downloads:c:\Downloads mcr.microsoft.com/windows:20H2 powershell -command 'C:\Downloads\chezmoi.exe init --verbose --source C:\Downloads; C:\Downloads\chezmoi.exe data --verbose --source C:\Downloads'
{
  "chezmoi": {
    "arch": "amd64",
    "fqdnHostname": "7d2ad3306736",
    "homeDir": "C:\\Users\\ContainerAdministrator",
    "homedir": "C:\\Users\\ContainerAdministrator",
    "hostname": "7d2ad3306736",
    "kernel": null,
    "os": "windows",
    "osRelease": {},
    "sourceDir": "C:/Downloads",
    "username": "User Manager\\ContainerAdministrator",
    "version": {
      "builtBy": "goreleaser",
      "commit": "56485778b5334f3aa05b5d12abff0db00cc8cb2b",
      "date": "2021-03-28T18:30:09Z",
      "version": "v2.0.4-SNAPSHOT-5648577"
    }
  },
  "email": "user@example.com"
}
> docker run -ti -v c:\Users\felip\Downloads:c:\Downloads mcr.microsoft.com/windows:20H2 powershell -command 'C:\Downloads\chezmoi.exe init --verbose --source C:\Downloads; C:\Downloads\chezmoi.exe data --verbose --source C:\Downloads'
email? teste
{
  "chezmoi": {
    "arch": "amd64",
    "fqdnHostname": "9e5d16128b04",
    "homeDir": "C:\\Users\\ContainerAdministrator",
    "homedir": "C:\\Users\\ContainerAdministrator",
    "hostname": "9e5d16128b04",
    "kernel": null,
    "os": "windows",
    "osRelease": {},
    "sourceDir": "C:/Downloads",
    "username": "User Manager\\ContainerAdministrator",
    "version": {
      "builtBy": "goreleaser",
      "commit": "56485778b5334f3aa05b5d12abff0db00cc8cb2b",
      "date": "2021-03-28T18:30:09Z",
      "version": "v2.0.4-SNAPSHOT-5648577"
    }
  },
  "email": "teste"
}
```

**Comment by felipecrs** [comment]
If you want me to test anything, feel free to ask me. It took me a while to setup this Windows containers environment, hahaha.

**Comment by twpayne** [comment]
Thanks so much for the testing @felipecrs :)

I had no idea that Windows container environments existed. This is potentially really interesting for CI.

**Comment by felipecrs** [comment]
Yeah... the only caveat is that you need a Windows host, and the Windows docker image is around 6GB to pull. There are smaller ones, such as the Windows Nano Server (150MB), but sadly `chezmoi` could not run due to missing DLLs.

**Comment by twpayne** [comment]
Ah, thanks. It also looks like you need Windows 10 Pro to run Windows images, and I only have Windows 10 Home on my laptop.

**Pull request merged**
