### PR TITLE
feat: Support 1Password CLI 2.0

### LINKED ISSUE #1860: Support 1Password CLI 2.0
## Is your feature request related to a problem? Please describe.
Currently, when using the 1Password CLI beta, my template file with a 1Password document fails and breaks `chezmoi apply`.

## Describe the solution you'd like

Chezmoi should check `op -v` and change the syntax appropriately. 

## Describe alternatives you've considered

I could downgrade back to 1.0 but that defeats the purpose of beta testing.

## Additional context

Instructions on the new CLI can be found [here](https://developer.1password.com/docs/cli/upgrade/).

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #1860.
Closes #1828.
cc @cadenkriese

This builds on @kdomanski's work in #1828 (commit is co-authored by @kdomanski) to take into account the refactoring of template functions in #1859 and further refactoring.

At this instant, I believe the code is correct, but there's a bug in the tests that get confused by existing `OP_SESSION_` environment variables, and I'm most of the way through fixing it.

This, [raised by @kdomanski](https://github.com/twpayne/chezmoi/pull/1828#issue-1106185987), still needs to be addressed:

> With the changed API structure IMO I'd reconsider whether having both `onepasswordDetailsFields` and `onepasswordItemFields` with different behavior makes sense. As far as I can tell, all fields are now returned in one array, but some have a Section field and some don't.

Note that as the structure of the data returned by 1Password CLI 2.0 is different to 1Password CLI 1.x, users will have to update their templates when they switch to version 2 anyhow.

### CODE REVIEW

**Comment by twpayne** [comment]
This is now ready for review and testing.

**Comment by twpayne** [comment]
These are the changes I had to make to my source state to support the new 1Password CLI:

https://github.com/twpayne/dotfiles/commit/5d1ee37b1edbf159394deb510214e2dd2856f959

**Comment by cadenkriese** [comment]
Okay, I'm testing it out, and I'm not sure if this is my fault or not, but I get this error on `chezmoi apply`
```
chezmoi: template: dot_ssh/private_id_ed25519.tmpl:1:4: executing "dot_ssh/private_id_ed25519.tmpl" at <onepasswordDocument "document_id">: error calling onepasswordDocument: /usr/local/bin/op signin --raw: exit status 1`
```
The contents of private_id_ed25519.tmpl are:
```
{{- onepasswordDocument "document_id" -}}
```

**Comment by twpayne** [comment]
Thanks for testing.

What's the output of

```
$ chezmoi --debug execute-template '{{- onepasswordDocument "document_id" -}}' >/dev/null
```
?

You'll need to redact the session key from the output before posting it here.

**Comment by cadenkriese** [comment]
Here's what I get; it looks like it doesn't even reach anything with a session key?

<details>
  <summary>Output</summary>

```
❯ chezmoi --debug execute-template '{{- onepasswordDocument "document_id" -}}' >/dev/null
2022-01-31T15:08:58-07:00 INF persistentPreRunRootE args=["chezmoi","--debug","execute-template","{{- onepasswordDocument \"document_id\" -}}"] goVersion=go1.17.6 version={"builtBy":"","commit":"","date":"","version":""}
2022-01-31T15:08:58-07:00 INF Stat component=system name=/Users/caden/.local/share/chezmoi/.git
2022-01-31T15:08:58-07:00 ERR ReadFile error="open /Users/caden/.local/share/chezmoi/.chezmoiversion: no such file or directory" component=system data= name=/Users/caden/.local/share/chezmoi/.chezmoiversion size=0
2022-01-31T15:08:58-07:00 ERR ReadFile error="open /Users/caden/.local/share/chezmoi/.chezmoiroot: no such file or directory" component=system data= name=/Users/caden/.local/share/chezmoi/.chezmoiroot size=0
2022-01-31T15:08:58-07:00 INF Stat component=system name=/Users/caden/.local/share/chezmoi
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/refs
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/info
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/logs
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/refs/tags
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/pack
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/logs/refs
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/refs/heads
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/refs/remotes
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/b6
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/64
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/cc
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/refs/remotes/origin
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/hooks
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/b7
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/99
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/logs/refs/remotes
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/07
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/79
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/7b
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/logs/refs/remotes/origin
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/1c
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/4f
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/7a
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/82
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/dc
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/24
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/info
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/0a
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/logs/refs/heads
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/0f
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/52
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/3b
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/ca
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/55
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/10
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/12
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects/86
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/dot_ssh
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/dot_config
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/dot_config/iterm2
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/dot_config/neofetch
2022-01-31T15:08:58-07:00 ERR ReadFile error="open /etc/os-release: no such file or directory" component=system data= name=/etc/os-release size=0
2022-01-31T15:08:58-07:00 ERR ReadFile error="open /usr/lib/os-release: no such file or directory" component=system data= name=/usr/lib/os-release size=0
2022-01-31T15:08:58-07:00 INF chezmoi.OSRelease error="file does not exist"
2022-01-31T15:08:58-07:00 INF Output args=["op","--version"] duration=36.839417ms output="2.0.0-beta.12\n" path=/usr/local/bin/op size=14
2022-01-31T15:08:58-07:00 INF IdempotentCmdOutput args=["op","--version"] component=system output="2.0.0-beta.12\n" path=/usr/local/bin/op
chezmoi: template: arg1:1:4: executing "arg1" at <onepasswordDocument "document_id">: error calling onepasswordDocument: /usr/local/bin/op signin --raw: exit status 1
```
</details>

**Comment by twpayne** [comment]
> Here's what I get; it looks like it doesn't even reach anything with a session key?

Please could you retry with the most recent code in this PR (which I just pushed).

Also, it's weird that the following command failed. What happens if you run just this?
```console
$ /usr/local/bin/op signin --raw
```

**Comment by twpayne** [comment]
This is also strange in the log output:

```
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/objects
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/refs
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/info
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/logs
2022-01-31T15:08:58-07:00 INF ReadDir component=system name=/Users/caden/.local/share/chezmoi/.git/refs/tags
```

chezmoi should ignore directories beginning with a `.`, yet here we see that it recurses into the `.git` directory.

What's the output of the following two commands:

```console
$ which chezmoi
```

```console
$ chezmoi doctor
```

?

**Comment by cadenkriese** [comment]
Okay, I've found out that the sign-in issues were due to the new biometric unlock. After reading through their documentation and understanding the gist of your implementation, I suggested that they make this behavior more consistent or add additional information.

As for the recursion, issue,
```
❯ which chezmoi
/usr/local/bin/chezmoi
```
```
❯ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              dev
ok        os-arch              darwin/arm64
ok        uname                Darwin Cadens-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
ok        go-version           go1.17.6 (gc)
ok        executable           /usr/local/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /bin/zsh
ok        edit-command         found /opt/homebrew/bin/vi
ok        umask                022
ok        git-command          found /opt/homebrew/bin/git, version 2.35.1
ok        merge-command        found /opt/homebrew/bin/vimdiff
info      age-command          age not found in $PATH
ok        gpg-command          found /opt/homebrew/bin/gpg, version 2.3.4
info      pinentry-command     not set
ok        1password-command    found /usr/local/bin/op, version 2.0.0-beta.12
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

**Comment by twpayne** [comment]
Thank you again @kdomanski for the contribution and kick-start and @cadenkriese for the testing. I think we can merge this now.

For the recursion issue, I'm not sure what's going on, and haven't been able to reproduce it yet. At the moment it's harmless, but if you do spot anything weird, then please do report it.

**Pull request merged**
