### PR TITLE
[RFC] feat: Consider file order in chezmoi config arguments

### PR DESCRIPTION
**Pull request by Mephistophiles**
This commit overrides `reverse` (false -> true) if `{{ .Target }}` stands first in `diff.args`.

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks for this. I think I understand what it does, but could you explain why it's needed?

**Comment by Mephistophiles** [comment]
this allow to enable pernanent "reverse" mode for the diff command.  although I can just put the reverse flag in the config ...

**Comment by twpayne** [comment]
> although I can just put the reverse flag in the config ...

Indeed. You can also reverse the args directly in `diff.args`. So, I think the functionality in this PR is already available in chezmoi, so I do not think this PR is needed. What do you think?

**Comment by twpayne** [comment]
I've created #1951 to add the `diff.reverse` configuration variable.

**Comment by Mephistophiles** [comment]
It is good enough for me! Thanks!
This PR is not longer need.

**Pull request closed without merging**
