### PR TITLE
feat: Add archive-file externals

### LINKED ISSUE #3079: Allow getting files from tar / zip without shelling out
## Is your feature request related to a problem? Please describe.

Given that Windows seems to have issues with filter.args for `tar`, it might be better to have the option for chezmoi to pull the file itself.

## Describe the solution you'd like

When using "type: file", don't shell out, or maybe have a "type: archive-file" that doesn't shell out.

## Describe alternatives you've considered

I've tried hacking around with tar on Windows, but can't seem to get it to be happy.

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #3079.
Refs #3069.
Refs #3072.

@Sacro is this what you had in mind? Would you be able to test this?

### CODE REVIEW

**Comment by Sacro** [comment]
This is exactly what I had in mind. 

I've converted all my externals to use this, and it works beautifully on Windows and Linux.

https://github.com/Sacro/dotfiles/commit/71fad7d97606ea5841802b763d9b31d310cbae71

**Comment by felipecrs** [comment]
Wow, this is amazing!

**Comment by dhruvinsh** [comment]
does the `archive-file` only mean to support `.tar.gz` files? can it be expanded to work with `.gz` files? 

```jinja-toml
.local/bin/taplo:
  type: file
  url: >-
    https://github.com/tamasfe/taplo/releases/download/0.8.0/taplo-full-linux-x86_64.gz
  executable: true
  path: taplo
  filter:
    command: gzip
    args:
      - "-d"
```

**Comment by twpayne** [comment]
`archive-file` works on archives (`.tar` and `.zip`) and supports several compression methods.

In your case you have a compressed file, not an archive, so the use of `filter.command` and `filter.args` is correct.

**Comment by dhruvinsh** [comment]
Good to know difference between compressed and archive. :) Thanks.

**Pull request merged**
