### PR TITLE
Documentation: Clarified what 'source state' means

### PR DESCRIPTION
**Pull request by tcholewik**
No functionality changes,just updated documentation to be little more explicit.
I just wasted more time that I care to admit by misinterpreting what `source sate` means.

### CODE REVIEW

**Comment by bradenhilton** [comment]
Is this incomplete? It only clarifies what source state means on the doc page for `.chezmoiexternal` and does not mention that `.chezmoiroot` must be in the root of the source directory.

@twpayne I'm assuming either you struggled finding a more appropriate naming convention (naming things can be difficult) or I'm just not able to easily reason about it, but I must admit I also find the differences between "<source/target/destination> <state/directory>" confusing sometimes.

Based on my current understanding, which essentially boils down to "the source directory is where chezmoi looks for the source state, and the source state is how you would like your home directory to look", I find the following to be especially confusing:

- The [`.chezmoiroot` doc page](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiroot/) explains that `.chezmoiroot` can change where the source _state_ is read from relative to the source _directory_.
- The ["Customize your source directory" doc page](https://www.chezmoi.io/user-guide/advanced/customize-your-source-directory/) also explains how to use `.chezmoiroot` to change where the source _state_ is read from.
- The ["Source state attributes" doc page](https://www.chezmoi.io/reference/source-state-attributes/) briefly explains how to change the source _directory_ with `-S` or `sourceDir`.

I think much of this confusion is based on the fact that (the directory of) source _state_ and source _directory_ both are the same location on a default install, but they can both be changed independently.

Perhaps the ["Getting started" section on the home page](https://www.chezmoi.io/#getting-started) should explicitly direct users to the [Concepts doc page](https://www.chezmoi.io/reference/concepts/)? It directs users to the ["User guide" doc page](https://www.chezmoi.io/user-guide/setup/) where "source state" is mentioned several times, but a new user navigating through the pages in the recommended order in "Getting started" does not yet know what this means, and it's not immediately obvious that it's explained in Reference➜Concepts.

I wouldn't mind opening some draft/WIP PRs to overhaul some of the doc pages.

Just putting thoughts to words really.

**Comment by twpayne** [comment]
Thank you, I'd love for chezmoi get better documentation around this :)

The [concepts page in the reference guide](https://www.chezmoi.io/reference/concepts/) is my attempt to name things, and was the main reason for the v2 rewrite. There's a [really nice graphic](https://lh3.googleusercontent.com/-uQxHiKwQBiWUuKr7-TjVtn-odX4g9YBNlJHGL35GwRsDGoEIUEagFd157pCO1KY9QBdY5GuUQ7M5X4WVlzQmL_HGzl3qtb9Nng-Tn6eIMeVaAfHOTdnPuyzrNESLSZZ0Ruw2mn1)  from @ihommani that should help.

**Comment by twpayne** [comment]
> Is this incomplete? It only clarifies what source state means on the doc page for `.chezmoiexternal` and does not mention that `.chezmoiroot` must be in the root of the source directory.

Yes, you are correct. This PR is incomplete on many levels (the change described would be better placed elsewhere, there's invalid markdown formatting,, and there's no indication that the original author followed the [contributing guide](https://www.chezmoi.io/developer/contributing-changes/). What I did was merge the PR, fix the problems, and force-push a commit that kept the useful changes.

At the same time, as a maintainer, I'm always happy to encourage new contributions. At the same time, many contributions are drive-by commits that take more time to review than to fix (especially with the back-and-forth discussion in a PR). So, I reserve my time and proper reviews for repeated contributors like @bradenhilton :)

**Comment by twpayne** [comment]
#2173 hopefully improves the documentation on concepts.

**Pull request merged**
