### PR TITLE
chore: fix website build by pinning mkdocs version to 1.4.3

### PR DESCRIPTION
**Pull request by catay**
Temporary fix for the build website workflow until they fix upstream.

https://github.com/mkdocs/mkdocs/issues/3310
https://github.com/fralau/mkdocs-mermaid2-plugin/issues/80

### CODE REVIEW

**Comment by twpayne** [comment]
I prefer this approach to #3119.

Would you mind including only the changes to `.github/workflows/main.yaml` in this PR? I'll then merge this and then rebase other PRs.

**Comment by halostatue** [comment]
I would suggest rebasing this interactively and dropping all but the `chore` so that it doesn’t include the other branch in it.

**Comment by catay** [comment]
Oops, sorry, I thought branched from master ... but didn't,  give me a few minutes.

**Review by halostatue — APPROVED** [review]

**Comment by halostatue** [comment]
@twpayne The merge button issue appears to be something affecting a [number of repos on GitHub](https://github.com/orgs/community/discussions/51612). One user suggested [a workaround](https://github.com/orgs/community/discussions/51612#discussioncomment-6554628).

**Pull request merged**
