### PR TITLE
feat: Add gitHubLatestRelease template function

### LINKED ISSUE #1637: Add gitHubLatestRelease template function
## Is your feature request related to a problem? Please describe.

Using the [Get the latest release](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) api allows us to easily retrieve information about the latest release.

## Describe the solution you'd like

Add  `gitHubLatestRelease` template function to support the [Get the latest release](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) api.

## Describe alternatives you've considered

n/a

## Additional context

> With only the [Get a repository](https://docs.github.com/en/rest/reference/repos#get-a-repository) api, it may still not be quite what I expected
> i would like to at least provide [Get the latest release](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) functionality
> probably an easy way to do this is to add another templateFunc like `gitHubLatestRelease`

Ref: #1633

### PR DESCRIPTION
**Pull request by MuXiu1997**
Fixes #1637.

### CODE REVIEW

**Comment by MuXiu1997** [comment]
Sorry, I was too impatient, I just used my local `golangci-lint` to check and then submitted

**Comment by twpayne** [comment]
Thank you - this looks great! Please could you squash the commits into a single commit - this will help keep the release notes short and free of noise.

**Comment by MuXiu1997** [comment]
Thanks, I learned a lot!

**Comment by MuXiu1997** [comment]
Hey~ 😃
github seems to be able to squash multiple commits when merging pr, I haven't tried it and don't know if it works for you
ref: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#merge-message-for-a-squash-merge

**Comment by twpayne** [comment]
Yes, I'm aware that GitHub supports this. However, I don't want to use it as often a PR will consist of multiple logically separate commits, and having more, precise commits greatly assists when reading the history, when using `git bisect`, and can more precisely be reverted if they introduce a problem.

**Comment by MuXiu1997** [comment]
Thanks, I understand~

**Pull request merged**
