### PR TITLE
Enhance Codespaces documentation

### PR DESCRIPTION
**Pull request by felipecassiors**
- Set `sourceDir` so further calls of `chezmoi` will pick-up the right source directory without need to `--source`.

- Install `chezmoi` to a known binary folder, only if it's not installed already.

- A safer installation script (because of `set -e`).

Closes https://github.com/twpayne/chezmoi/issues/760 and closes https://github.com/twpayne/chezmoi/issues/818.

### CODE REVIEW

**Comment by felipecassiors** [comment]
The `install` script can be used anywhere, not only on Codespaces. For example, I always install my dotfiles in a new machine with a singles command:

```bash
sh -c "$(curl -fsSL https://git.io/felipecassiors-dotfiles)"
```
https://github.com/felipecassiors/dotfiles#using-the-convenience-script

Under the hoods, it installs `git` if needed, clones the repository to my preferred location (~/.dotfiles) and then calls the script `install`.

**Comment by felipecassiors** [comment]
There is a bunch of verbosities though, do you think it would be better to take them off the documentation?

**Comment by felipecassiors** [comment]
I don't understand why the CI is complaining...

**Comment by twpayne** [comment]
Thanks very much for this -- these are really nice improvements.

The CI is complaining because it is necessary to run `go generate` and include any changes it makes after making changes to the documentation, see [this section of the contributing guide](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#generated-code) for an explanation.

**Comment by felipecassiors** [comment]
My bad, I should have looked at the contribution guidelines. Fixed now, by the way.

**Comment by twpayne** [comment]
Thank you @felipecassiors for this great contribution :)

**Comment by felipecassiors** [comment]
By the way, I used the `devcontainer` to run the `go generate` and it worked quite well.

**Pull request merged**
