### PR TITLE
feat: Add read-source-state hook

### PR DESCRIPTION
**Pull request by twpayne**
Refs #3342.

Work in progress. Small code change, big impact. Feedback appreciated.

### CODE REVIEW

**Comment by halostatue** [comment]
Seems like a potentially powerful change, as you say.

**Comment by twpayne** [comment]
@bradenhilton @nandalopes @felipecrs I would appreciate your input on this.

**Comment by felipecrs** [comment]
I will carefully analyze and provide my feedback in some hours.

**Comment by twpayne** [comment]
No stress felipecrs and @halostatue I didn't mention because you're already in the conversation :)

**Comment by felipecrs** [comment]
I believe this is a nice change. It will also be useful to install tools required by `output` template calls, like `curl` or `git`.

**Comment by halostatue** [comment]
The code and documentation looks good. I think my main concern is that the commands need to be specified "full path". I'm not sure that there's a good workaround for this.

**Comment by bradenhilton** [comment]
Would the password manager part benefit from being more general instead? A password manager is just one of many potential prerequisites as @felipecrs pointed out.

Either way, this is great.

**Review by halostatue — APPROVED** [review]

**Comment by twpayne** [comment]
Thank you all for the reviews!

> I think my main concern is that the commands need to be specified "full path". I'm not sure that there's a good workaround for this.

Good point. It would be nice if the path to the `read-source-state` hook command was relative to the source directory.

One way I can think of doing this is by overriding the command (i.e. first checking for the command relative to the source state directory, and only afterwards falling back to the user's $PATH), but this falls foul of chezmoi's "the source state consists of only regular files and directories" principle as it would require the hook command to be executable in the source state.

Another way would be to use an explicit interpreter, something like:

```toml
[hooks.read-source-state.pre]
    command = "sh"
    args = ["-c", ".local/share/chezmoi/.install-password-manager.sh"]
```

Thoughts?

> Would the password manager part benefit from being more general instead? A password manager is just one of many potential prerequisites as @felipecrs pointed out.

Yes, absolutely! I used the password manager example as it's a problem that I personally have (on a new machine I need to install and setup 1Password before I can deploy my dotfiles). It would be great to have some more examples of adding prerequisites.

**Pull request merged**
