### PR TITLE
fix: Implement some logic for `isExecutable` for windows

### PR DESCRIPTION
**Pull request by arran4**
This is based on:
* https://www.nextofwindows.com/what-is-pathext-environment-variable-in-windows
* It goes back to at least Windows XP: https://ss64.com/nt/syntax-variables.html potentially further

fix: Provide some logic for `isExecutable` under windows for determining if it's an executable

BREAKING CHANGE: `isExecutable` no longer always returns false and tries to determine execution status by file extension

### CODE REVIEW

**Review by halostatue — COMMENTED** [review]
This looks good to me. I’m going to defer approval to @twpayne because it is a breaking change, but I think that it’s a *sensible* change. I do not expect that anything is depending on `isExecutable` returning false on Windows, but [Hyrum’s law](https://www.hyrumslaw.com) always applies.

**Comment by arran4** [comment]
I think it is primarily used for one of the source control systems. In which case it might need to be split.

> Defining the correct level of abstraction is a completely separate discussion (see Mythical Man-Month)

I don't remember that being in the book, but means I can refer to it a lot more. The 70s man..

**Comment by twpayne** [comment]
Thanks, this makes sense. There are few minor changes I'd like to do to make the control flow more compact, but I'll do this in a separate PR.

**Comment by arran4** [comment]
Thanks I will read.

**Pull request merged**
