### PR TITLE
feat: Add jq template function

### PR DESCRIPTION
**Pull request by twpayne**
Refs #2826.

### CODE REVIEW

**Comment by halostatue** [comment]
I’m getting an unexpected `[]` wrapping the output:

```console
$ go run . execute-template '{{ dict "hello" 1  | jq "." | toJson }}'
[{"hello":1}]
$ go run . execute-template '{{ 1  | jq "." | toJson }}'
[1]⏎
```

**Comment by halostatue** [comment]
This is going to lead to very hard to read template functions:

```
op document list --format json |
  go run . execute-template --with-stdin \
    '{{ .chezmoi.stdin | fromJson | jq ". | map(select(.title | startswith(\"aws-credentials: \")) | { (.title): .id }) | add" | first | toJson }}'
```

I’m also not sure how I would embed dynamic variables given the overloading of `.` and the fact that the JQ source string isn’t a template itself.

I don’t think this is a bad addition, but I don’t know how *useful* it will be.

**Comment by halostatue** [comment]
I think that this will be more useful if we approach the jq source file as `. | jq (includeTemplate "…" (data))`. There’s no need for any additional functions (I was going to suggest `jqFile`, but that probably isn’t necessary with `include` and `includeTemplate`).

**Review by halostatue — APPROVED** [review]
We should be on the lookout for more complex examples to demonstrate, because the value of `jq` here will be in the *flexibility* provided.

**Comment by twpayne** [comment]
> I don’t think this is a bad addition, but I don’t know how _useful_ it will be.

That's a very fair point. I'll close this PR for now. We can re-open it if it turns out that there's a good use for this functionality.

**Comment by twpayne** [comment]
Re-opening as @halostatue identified a possible use case in https://github.com/twpayne/chezmoi/discussions/2864#discussioncomment-5338970.

Another use case is a replacement for some of the password manager functions like [`onepasswordDetailsFields`](https://www.chezmoi.io/reference/templates/1password-functions/onepasswordDetailsFields/) and [`bitwardenFields`](https://www.chezmoi.io/reference/templates/bitwarden-functions/bitwardenFields/). In short, the `jq` template function allows extraction of specific data from complex structures in a succinct way.

**Comment by halostatue** [comment]
It would be nice to have this be able to call out to `jq` instead of using `gojq` *if desired* (similar to opting into the built-in `age`, but instead opting into the use of the `jq` binary).

**Pull request merged**
