### PR TITLE
Added --template-symlinks-home and --template-symlinks-source options

### PR DESCRIPTION
**Pull request by Flygrounder**
This is not a finished work, opening a PR to discuss changes. 
I am trying to add functionality, described in #1075. I've added a basic implementation of templating symlinks with targets inside home, that replaces `s.destDirAbsPath` with `{{ .chezmoi.homedir }}`.
To test this functionality, you can run `chezmoi add --template-symlinks-home <your_symlink>`

 I am struggling with adding a test for this functionality. The problem is when I add an absolute symlink in test, it points to `/tmp/go-vfs-vfst3713338411/home/user/.dir/subdir/file`, not `/home/user/.dir/subdir/file`. Are there any workarounds?

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks very much for this!

For the tests, it's probably easiest to use a [`testscript`](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript) test for this, like the existing tests in [`testdata/scripts`](https://github.com/twpayne/chezmoi/tree/master/testdata/scripts).  Within these tests, the variable `HOME` points to the temporary home directory. This means that you'll probably want something like the following in `testdata/scripts/symlinks_templatesymlinkshome.txt`:

```
mkhome

# test that chezmoi add --template-symlinks-home creates an absolute symlink
symlink .symlink -> .dir/subdir/file
chezmoi add --template-symlinks-home $HOME${/}.symlink
chezmoi cat $HOME${/}.symlink
stdout ${HOME@R}/.dir/subdir/file
```

Warning: I haven't tested this, so it might need a couple of tweaks.

**Comment by Flygrounder** [comment]
At this point, this PR should close #1075

**Comment by twpayne** [comment]
Thanks very much for this. Would you mind squashing all the commits into a single commit?

**Comment by Flygrounder** [comment]
No problems, you can squash them if you find this appropriate

**Comment by twpayne** [comment]
Thank you very much @Flygrounder :)

**Pull request merged**
