### PR TITLE
fix: Use builtin age when encryption is unset

### LINKED ISSUE #3980: Builtin age doesn't work
## Describe the bug

From docs (https://www.chezmoi.io/user-guide/encryption/age/#builtin-age-encryption):
```
chezmoi has builtin support for age encryption which is automatically used if the age command is not found in $PATH.
```

I configured `age` to be installed via `.chezmoiexternal.toml`:
```toml
[".local/bin/age"]
    type = "archive-file"
    url = "https://dl.filippo.io/age/latest?for=linux/amd64"
    path = "age/age"
    executable = true
    refreshPeriod = "168h"
```

But `czm apply` fails with:
```console
$ czm apply
chezmoi: .config/zsh/config.d/work.zsh: exec: "age": executable file not found in $PATH
```

`externals` files are processed in order of target names, that's mentioned in docs. I guess I can put age to `.bin` to make it work, although I'd like keep binaries where they are currently. And ideally remove dependency on age completely from my setup.

`chezmoi age` doesn't work here either but I guess this is expected, although a bit confusing:
```console
$ chezmoi age decrypt dot_config/zsh/config.d/encrypted_work.zsh.tmpl.age
chezmoi: only passphrase encryption is supported
```

**So is it no longer supported and docs are outdated or something is broken here?**

## To reproduce

With `age` uninstalled:
```console
$ chezmoi decrypt --verbose dot_config/zsh/config.d/encrypted_work.zsh.tmpl.age
chezmoi: exec: "age": executable file not found in $PATH
```

Adding `--use-builtin-age on` doesn't show any errors:
```console
$ chezmoi --use-builtin-age on --verbose decrypt dot_config/zsh/config.d/encrypted_work.zsh.tmpl.age
chezmoi: exec: "age": executable file not found in $PATH
```

age config in `.config/chezmoi/chezmoi.toml`:
```toml
encryption = "age"

[age]
    identity = "~/.config/chezmoi/key.txt"
    recipient = "age1p6n7pr73yfxysh8qjty4guhfea9gqgh7uwk8w6e3wx7r9eqqw4sqeg4r9g"
```

Tested on Linux (x64), Mac (arm64) and Windows (x64).

## Expected behavior

Builtin age is used.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.52.3, commit c136cd0324b46d311427eaf8ebff3d4532effbb1, built at 2024-09-30T09:03:56Z, built by goreleaser
warning   latest-version              v2.52.4
ok        os-arch                     linux/amd64 (CentOS Stream 9)
ok        uname                       Linux hostname 5.19.0-0 #1 SMP Fri Jan 1 12:00:00 PST 2024 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version                  go1.23.1 (gc)
ok        executable                  ~/.local/bin/chezmoi
ok        upgrade-method              replace-executable
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-10-10T06:52:17-07:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
info      diff-command                not set
ok        edit-command                found /usr/bin/nvim
ok        edit-args                   /usr/bin/nvim
ok        git-command                 found /usr/local/bin/git, version 2.43.5
ok        merge-command               found /usr/bin/nvim
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.3.3
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

### PR DESCRIPTION
**Pull request by KapJI**
* If `[age]` config is present but `encryption` is not set, respect `useBuiltinAge` config anyway. This behaviour is aligned with chezmoi docs. Remove confusing comment, encryption is used only when either `[age]` or `[gpg]` configs are provided.
* Because having age or gpg configs with `encryption` not set is unexpected, show warning about that.
* Add bunch of unit tests to check new behaviour.

This is the first time I'm writing in Go, I'd appreciate your feedback.

Fixes #3980

### CODE REVIEW

**Comment by KapJI** [comment]
I  see that you prefer rebase and merge to squashing commits in PRs here. Do you want me to force push it as a single commit with the correct title?

**Comment by twpayne** [comment]
> I see that you prefer rebase and merge to squashing commits in PRs here. Do you want me to force push it as a single commit with the correct title?

Yes please.

For info, chezmoi also has testscript-based tests in https://github.com/twpayne/chezmoi/tree/bea13383eec62e8a61444b4d9b6cbf6282056621/internal/cmd/testdata/scripts, which are often quicker to write than full Go unit tests for functionality like in this PR.

**Comment by KapJI** [comment]
> chezmoi also has testscript-based tests

Yes, I've seen those. I wanted to check computed values in `c.encryption` and `c.Age.UseBuiltin` to make sure they are set to expected values.

**Comment by KapJI** [comment]
About deleted comment. I just manually tested case when chezmoi tries to decrypt `.age` file while no encryption is set in the config (neither `encryption` nor `[age]`). Both before and after it printed `no encryption` message as expected.

**Comment by twpayne** [comment]
Great, thank you very much for this :)

**Pull request merged**
