### PR TITLE
feat: Add gitHubRepo template function

### LINKED ISSUE #1632: Add some templateFunc about githubRepo
## Is your feature request related to a problem? Please describe.

I feel some inconvenience when I managed some plugins such as oh-my-zsh plugin or ranger plugin with `.chezmoiexternal` .

  - A plugin is usually a github repo, and I may need to do a lot of repetitive work when I'm writing `.chezmoiexternal`

  - I can't seem to get the url of the latest release easily

hence I would like `chezmoi` to provide a templateFunc like `gitHubRepo` to get some information about the github repo.

## Describe the solution you'd like

```yaml
# .chezmoiexternal.yaml

# Oh-my-zsh plugins
{{ $repos := list
    # gitHubRepo <github-repo-fullname> [ref]
    (gitHubRepo "jeffreytse/zsh-vi-mode")
    (gitHubRepo "zsh-users/zsh-syntax-highlighting" "heads/master")
    # assuming it exists
    (gitHubRepo "foo/bar" "heads/main")
-}}
{{ range ($repos) -}}
.oh-my-zsh/custom/plugins/{{ .name }}:
  type: "archive"
  url: "{{ default .archive .latestArchive }}"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
{{ end -}}
```

And output:

```yaml
# .chezmoiexternal.yaml

# Oh-my-zsh plugins
.oh-my-zsh/custom/plugins/zsh-vi-mode:
  type: "archive"
  url: "https://api.github.com/repos/jeffreytse/zsh-vi-mode/tarball/v0.8.5" # latest releases
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/zsh-syntax-highlighting:
  type: "archive"
  url: "https://api.github.com/repos/zsh-users/zsh-syntax-highlighting/tarball/heads/master"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
.oh-my-zsh/custom/plugins/bar:
  type: "archive"
  url: "https://api.github.com/repos/foo/bar/tarball/heads/main"
  exact: true
  stripComponents: 1
  refreshPeriod: "168h"
```

## Describe alternatives you've considered

n/a

## Additional context

I love `chezomi`, thank you for everything you've done for this AMAZING project!

and sorry for my poor English~

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #1632.

Review welcome.

cc @felipecrs @MuXiu1997

### CODE REVIEW

**Comment by MuXiu1997** [comment]
With only the [Get a repository](https://docs.github.com/en/rest/reference/repos#get-a-repository) api, it may still not be quite what I expected
i would like to at least provide [Get the latest release](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) functionality
probably an easy way to do this is to add another templateFunc like `gitHubLatestRelease`

Also, it might be possible to store the response of the github api in [persistentState](https://github.com/twpayne/chezmoi/blob/434c29f49711f35a90bf07831c678f02b6136b95/internal/chezmoi/persistentstate.go#L18) like `githubApiStateBucket` to avoid repeated calls, ref: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests

Finally, I would like to try to implement the feature in #1633

**Comment by MuXiu1997** [comment]
I wanted to try to implement this feature myself at first, so I [open an issue](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#contributing-changes), but I didn't expect it to be implemented so quickly
If I have done something wrong please tell me, I am still a rookie
Perhaps my previous consideration was more for `archive` or `file`, and this is a more general solution
It would be helpful to support  `latest release` feature

You can ignore what I said before





> With only the [Get a repository](https://docs.github.com/en/rest/reference/repos#get-a-repository) api, it may still not be quite what I expected i would like to at least provide [Get the latest release](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) functionality probably an easy way to do this is to add another templateFunc like `gitHubLatestRelease`
> 
> Also, it might be possible to store the response of the github api in [persistentState](https://github.com/twpayne/chezmoi/blob/434c29f49711f35a90bf07831c678f02b6136b95/internal/chezmoi/persistentstate.go#L18) like `githubApiStateBucket` to avoid repeated calls, ref: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests
> 
> Finally, I would like to try to implement the feature in #1633

**Comment by twpayne** [comment]
> I wanted to try to implement this feature myself at first, so I [open an issue](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#contributing-changes), but I didn't expect it to be implemented so quickly
> If I have done something wrong please tell me, I am still a rookie

Sorry! I didn't realize. 

> With only the [Get a repository](https://docs.github.com/en/rest/reference/repos#get-a-repository) api, it may still not be quite what I expected i would like to at least provide [Get the latest release](https://docs.github.com/en/rest/reference/repos#get-the-latest-release) functionality probably an easy way to do this is to add another templateFunc like `gitHubLatestRelease`

This is a great idea, please open a new issue for this as the discussion in this PR will get lost when this PR is closed.

**Comment by MuXiu1997** [comment]
> This is a great idea, please open a new issue for this as the discussion in this PR will get lost when this PR is closed.

Thank you!
By the way, lest I misunderstand, did you agree with just

> probably an easy way to do this is to add another templateFunc like gitHubLatestRelease

or both

> probably an easy way to do this is to add another templateFunc like gitHubLatestRelease
>
> Also, it might be possible to store the response of the github api in persistentState like githubApiStateBucket to avoid repeated calls, ref: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests

**Comment by MuXiu1997** [comment]
I got it, Thank you~

and Thanks for great work!

**Review by MuXiu1997 — APPROVED** [review]
Thanks for great work~

**Comment by twpayne** [comment]
Is this template function actually needed? Or is the [`gitHubLatestRelease` function](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#githublatestrelease-user-repo) sufficient?

I only want to add this template function if it is absolutely needed.

**Comment by MuXiu1997** [comment]
At first I actually expected `gitHubRepo` to have more functionalities than just [Get a repository](https://docs.github.com/en/rest/reference/repos#get-a-repository), the main one being to [Get the latest release](https://docs.github.com/en/rest/reference/repos#get-the-latest-release).
So now this template function may provide less help

**Comment by twpayne** [comment]
Thanks for the feedback. Let's close this for now. We can always re-open it if needed.

**Pull request closed without merging**
