### PR TITLE
Remove keyring support

### PR DESCRIPTION
**Pull request by twpayne**
This is almost certainly not used as keyrings are machine-specific.

If you were using a keyring to store some secrets, please comment here or open an issue - it's easy to add back if needed.

### CODE REVIEW

**Comment by msafadieh** [comment]
Hey! Sorry to bother you but I actually use this feature and find it very useful.

I use KeePassXC as my OS keyring so I can easily manage them and back them up. chezmoi's built-in keepassxc plugin requires me to enter the master password each time I need to apply changes. By using `keyring` I can instead fetch the secrets from my already-running KeePassXC session.

**Comment by twpayne** [comment]
Whoops! Sorry about that. I'll restore the functionality now.

**Comment by twpayne** [comment]
@msafadieh What method(s) do you use to install chezmoi? I can tag a new version for you now if needed.

**Comment by msafadieh** [comment]
@twpayne I use the following methods:

- Arch Linux: `pacman -S chezmoi`
- Termux: `pkg install chezmoi`
- Other (amd64 Linux): I use the bootstrapping script

**Comment by twpayne** [comment]
Thanks for the swift response, and sorry for not releasing a new version yet. I'd like to understand the outcome of #905 and then tag a new version when we've resolved the problem there.

**Comment by twpayne** [comment]
I've now released version 1.8.7 which restores keyring support.

**Pull request merged**
