### PR TITLE
feat: Add plugin support

### PR DESCRIPTION
**Pull request by twpayne**
cc @felipecrs who previously requested plugin support (sorry I can't find the link)

### CODE REVIEW

**Comment by felipecrs** [comment]
That's super cool, can't wait to see what people will build around it.

For example, I could transform my `rootmoi` thing into a `chezmoi-root` plugin.

**Review by halostatue — APPROVED** [review]
Looks great.

**Comment by halostatue** [comment]
Two things that would be useful.

1. Expose the `$CHEZMOI_` environment variables.
2. Figure out a way to expose (possibly through a named pipe, FIFO, or something similar) the chezmoi context (`.data`).

The first should be pretty easy. The second will take some thinking and design, so should not be part of this PR.

**Comment by felipecrs** [comment]
The second can be passed through an environment variable like CHEZMOI_DATA='{"this": "is-json"}'

**Comment by halostatue** [comment]
> The second can be passed through an environment variable like CHEZMOI_DATA='{"this":"is-json"}'

Maybe, if the data is small (and I suspect it would be for most folks). I believe that some platforms (Windows?) have a maximum size on environment variable values. It’s ridiculously big (4k or 8k), but it is still limited.

**Comment by halostatue** [comment]
> 1. Expose the `$CHEZMOI_` environment variables.

Looking at the implementation again, I’m not sure that it would be easy. Both of these options should probably be follow-ups. If `.data` or other output is required, then `chezmoi execute-template` or `chezmoi data` can be called.

I think that the only thing we should *probably* do is set something like setting `CHEZMOI=1` and `CHEZMOI_PLUGIN=1`.

**Comment by twpayne** [comment]
Thanks for the reviews and comments. Let's :shipit: as-is.

**Pull request merged**
