### PR TITLE
feat: Add prompt*Once init template functions

### LINKED ISSUE #2184: Add prompt*Once functions to make prompting only for unset configuration values more ergonimic
## Is your feature request related to a problem? Please describe.

The docs describe the following pattern to only prompt for a config value if it is currently unset:
```
{{- $email := "" -}}
{{- if hasKey . "email" -}}
{{-   $email = .email -}}
{{- else -}}
{{-   $email = promptString "email" -}}
{{- end -}}

[data]
    email = {{ $email | quote }}
```

This is a bit cumbersome.

## Describe the solution you'd like

Add functions of the style `promptStringOnce`, `promptIntOnce`, etc. that only prompt if the config value is currently unset.

## Describe alternatives you've considered

Using the cumbersome pattern from the docs over and over, and/or trying to factor it out using Go's templates `define`.

## Additional context

Should this be added, the docs should be updated to reflect this as well.

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #2184.

WIP. Needs tests and documentation.

### CODE REVIEW

**Comment by twpayne** [comment]
@segevfiner I think this PR is correct. Would you be able to test it?

**Comment by segevfiner** [comment]
I probably will once I have the time for it.

**Comment by segevfiner** [comment]
Tried `promptStringOnce` without looking too much into the code in the PR. And it seems to work. I got prompted the first time for a value, and didn't get prompted again upon running `chezmoi init` again.

**Comment by twpayne** [comment]
Thank you for testing :)

**Comment by felipecrs** [comment]
I wonder if it is worth adding a new flag `init --prompt` to cause all `promptOnce` functions to re-prompt.

**Pull request merged**
