### PR TITLE
docs: Use get.chezmoi.io for install links

### PR DESCRIPTION
**Pull request by twpayne**
Refs #2430. cc @felipecrs 

I think this is correct. We should probably add an equivalent to `get.chezmoi.io` for PowerShell users.

### CODE REVIEW

**Comment by bradenhilton** [comment]
Is it possible to serve content dynamically based on the User Agent with GitHub pages? I tried searching but couldn't find a conclusive answer.

It would mean you could use the same link everywhere in the documentation, but it being dynamic would result in users with User Agent overrides being served incorrect content, so perhaps if we did that we should also offer `get.chezmoi.io/{ps1,sh}`?

**Comment by halostatue** [comment]
@bradenhilton Unfortunately, apparently not.

**Comment by felipecrs** [comment]
> We should probably add an equivalent to `get.chezmoi.io` for PowerShell users.

Hm... that's true. Well, maybe something like `get.chezmoi.io/ps1`?

**Comment by felipecrs** [comment]
> Is it possible to serve content dynamically based on the User Agent with GitHub pages? I tried searching but couldn't find a conclusive answer.

It's not possible, you have no access to an HTTP based reverse proxy configuration like nginx. The only way would be to use something else, like Cloudflare or Netlify.

**Pull request merged**
