### PR TITLE
feat: Use textconv with external diff commands

### LINKED ISSUE #4134: Binary diff doesn't work with textconv and custom diff command
## Describe the bug

When running `chezmoi diff`, the output does not reflect the configured `difft` command, but instead displays the binary diff as shown in the below verbose output. However, using `chezmoi apply` followed by the interactive diff correctly applies the `difft` command.

## To reproduce

1. Configure `chezmoi` with the provided settings:
   - Set `diff.command` to `"difft"`.
   - Define a custom `textconv` for `.plist` files like in [Diff - chezmoi - show human friendly diffs for binary files](https://www.chezmoi.io/user-guide/tools/diff/#show-human-friendly-diffs-for-binary-files).
2. Run `chezmoi diff` on a repository containing binary `.plist` files.
3. Observe the output of the `chezmoi diff` command.
4. Run `chezmoi apply` and interactively review the diff.
5. Observe that the interactive diff uses `difft` as expected.

## Expected behavior

The output of `chezmoi diff` should use the configured `difft` command for the `.plist` files, similar to the behavior of `chezmoi apply` with interactive diff.

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose diff
Library/Preferences/com.googlecode.iterm2.plist --- Binary
Binary contents changed.
```

## Output of chezmoi doctor

<details>
```console
RESULT   CHECK                       MESSAGE
ok       version                     v2.55.0, commit Homebrew, built at 2024-12-02T02:05:27Z, built by Homebrew
ok       latest-version              v2.55.0
ok       os-arch                     darwin/arm64
ok       uname                       Darwin Mac.station 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030 arm64
ok       go-version                  go1.23.3 (gc)
ok       executable                  /opt/homebrew/bin/chezmoi
ok       upgrade-method              brew-upgrade
ok       config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-12-10T18:10:57+01:00
ok       source-dir                  ~/.local/share/chezmoi is a git working tree (clean)
ok       suspicious-entries          no suspicious entries
ok       working-tree                ~/.local/share/chezmoi is a git working tree (clean)
ok       dest-dir                    ~ is a directory
ok       umask                       022
ok       cd-command                  found /bin/zsh
ok       cd-args                     /bin/zsh
ok       diff-command                found /opt/homebrew/bin/difft
ok       edit-command                found /opt/homebrew/bin/hx
ok       edit-args                   /opt/homebrew/bin/hx
ok       git-command                 found /usr/bin/git, version 2.39.5
ok       merge-command               found /usr/bin/vimdiff
ok       shell-command               found /bin/zsh
ok       shell-args                  /bin/zsh
info     age-command                 age not found in $PATH
ok       gpg-command                 found /opt/homebrew/bin/gpg, version 2.4.6
ok       pinentry-command            found /opt/homebrew/bin/pinentry-mac, version 1.1.1
info     1password-command           op not found in $PATH
ok       bitwarden-command           found ~/.local/bin/bw, version 2024.8.2
info     bitwarden-secrets-command   bws not found in $PATH
info     dashlane-command            dcli not found in $PATH
info     doppler-command             doppler not found in $PATH
info     gopass-command              gopass not found in $PATH
info     keepassxc-command           keepassxc-cli not found in $PATH
info     keepassxc-db                not set
info     keeper-command              keeper not found in $PATH
info     lastpass-command            lpass not found in $PATH
info     pass-command                pass not found in $PATH
info     passhole-command            ph not found in $PATH
info     rbw-command                 rbw not found in $PATH
info     vault-command               vault not found in $PATH
info     vlt-command                 vlt not found in $PATH
info     secret-command              not set
```
</details>

## Additional context

Configuration snippet:

```toml
[diff]
    command = "difft"

[[textconv]]
    pattern = "**/*.plist"
    command = "plutil"
    args = ["-convert", "xml1", "-o", "-", "-"]
```

The difft command works correctly during `chezmoi apply`, but it is not applied during `chezmoi diff`.

## Workaround

Actually it's possible to preview the diff with `chezmoi diff --use-builtin-diff`, but missing the specified `diff.command`

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #4134.

### CODE REVIEW

**Comment by twpayne** [comment]
@franzudev this is now ready for testing. Would you be able to test this?

**Comment by franzudev** [comment]
thanks for the help, still work like before. Here's the `chezmoi doctor` output:

<details>
RESULT    CHECK                       MESSAGE
warning   version                     dev, commit 3da497054f13c65f7131846bbc9715e5340165d1, built at 2024-12-12T01:46:20Z
warning   latest-version              v2.55.0
ok        os-arch                     darwin/arm64
ok        uname                       Darwin Mac.station 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030 arm64
ok        go-version                  go1.23.3 (gc)
ok        executable                  ~/chezmoi/chezmoi
ok        upgrade-method              replace-executable
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-12-10T18:10:57+01:00
ok        source-dir                  ~/.local/share/chezmoi is a git working tree (clean)
ok        suspicious-entries          no suspicious entries
ok        working-tree                ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
ok        diff-command                found /opt/homebrew/bin/difft
ok        edit-command                found /opt/homebrew/bin/hx
ok        edit-args                   /opt/homebrew/bin/hx
ok        git-command                 found /usr/bin/git, version 2.39.5
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /opt/homebrew/bin/gpg, version 2.4.6
ok        pinentry-command            found /opt/homebrew/bin/pinentry-mac, version 1.1.1
info      1password-command           op not found in $PATH
ok        bitwarden-command           found ~/.local/bin/bw, version 2024.8.2
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set

</details>

Let me know if you need anything else.

**Comment by twpayne** [comment]
Please share at least your config file so that other can reproduce what you see.

**Comment by franzudev** [comment]
> Please share at least your config file so that other can reproduce what you see.

here it goes:

```toml
encryption = "gpg"

[data]
    git_email = "user@gitserver.com"

[diff]
    command = "difft"

[edit]
    # https://github.com/twpayne/chezmoi/issues/3971#issuecomment-2393508601
    # workaround until the helix is capable of edit hardlinks
    hardlink = false

[git]
    autoCommit = true
    autoPush = true

[[textconv]]
    pattern = "**/*.plist"
    command = "plutil"
    args = ["-convert", "xml1", "-o", "-", "-"]

[gpg]
    recipient = "xxxxxxxxxxxxxxxx"
    args = ["--quiet"]
    
[pinentry]
    command = "pinentry-mac"

[scriptEnv]
    PYTHON_REQUIRED_VERSION = "3.12"
    VENV_NAME = "pyhome"
```

**Comment by franzudev** [comment]
After a couple of hours spent debugging, I've realized that maybe I've built it wrong or got confused with the system's one 😄

Apart from this the fix was perfect, thank you 🙏

```
./chezmoi diff
Library/Preferences/com.googlecode.iterm2.plist --- 1/3 --- XML
526         <integer>1</integer>                                                    526         <integer>1</integer>
527     </dict>                                                                     527     </dict>
528     <key>NSWindow Frame NSColorPanel</key>                                      528     <key>NSWindow Frame NSColorPanel</key>
529     <string>0 261 224 278 0 0 3360 1865 </string>                               529     <string>0 164 224 278 0 0 1920 1055 </string>
530     <key>NSWindow Frame NSNavPanelAutosaveName</key>                            530     <key>NSWindow Frame NSNavPanelAutosaveName</key>
531     <string>935 425 800 448 0 0 1920 1055 </string>                             531     <string>935 425 800 448 0 0 1920 1055 </string>
532     <key>NSWindow Frame SUStatusFrame</key>                                     532     <key>NSWindow Frame SUStatusFrame</key>

Library/Preferences/com.googlecode.iterm2.plist --- 2/3 --- XML
3007     </array>                                                                   3007     </array>
3008     <key>NoSyncBFPRecents</key>                                                3008     <key>NoSyncBFPRecents</key>
3009     <array>                                                                    3009     <array>
3010         <string>CommitMono Nerd Font Mono</string>                             3010         <string>CommitMono Nerd Font</string>
3011         <string>CommitMono Nerd Font</string>                                  3011         <string>FiraCode Nerd Font Mono</string>
3012         <string>MesloLGS NF</string>                                           3012         <string>MesloLGS NF</string>
3013     </array>                                                                   3013     </array>
3014     <key>NoSyncCommandHistoryHasEverBeenUsed</key>                             3014     <key>NoSyncCommandHistoryHasEverBeenUsed</key>

Library/Preferences/com.googlecode.iterm2.plist --- 3/3 --- XML
3023     <key>NoSyncFrame_SharedPreferences</key>                                   3023     <key>NoSyncFrame_SharedPreferences</key>
3024     <dict>                                                                     3024     <dict>
3025         <key>screenFrame</key>                                                 3025         <key>screenFrame</key>
3026         <string>{{0, 0}, {3360, 1890}}</string>                                3026         <string>{{0, 0}, {1920, 1080}}</string>
3027         <key>topLeft</key>                                                     3027         <key>topLeft</key>
3028         <string>{1448, 978}</string>                                           3028         <string>{862, 953}</string>
3029     </dict>                                                                    3029     </dict>
3030     <key>NoSyncHaveUsedCopyMode</key>                                          3030     <key>NoSyncHaveUsedCopyMode</key>
3031     <true/>                                                                    3031     <true/>
```

**Pull request merged**
