### PR TITLE
chore: Fix permissions for clear-pr-caches job

### PR DESCRIPTION
**Pull request by KapJI**
`DELETE /actions/caches` endpoint required `action: write` permission.

Failed job: https://github.com/twpayne/chezmoi/actions/runs/11769128068/job/32779753381

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks!

**Comment by twpayne** [comment]
Hmm, it looks like there's still a problem here: https://github.com/twpayne/chezmoi/actions/runs/11778245494/job/32804280956

**Comment by KapJI** [comment]
After this change permissions changed from
```
GITHUB_TOKEN Permissions
  Actions: read
  Attestations: read
  Checks: read
  Contents: read
  Deployments: read
  Discussions: read
  Issues: read
  Metadata: read
  Packages: read
  Pages: read
  PullRequests: read
  RepositoryProjects: read
  SecurityEvents: read
  Statuses: read
```
to
```
GITHUB_TOKEN Permissions
  Actions: read
  Metadata: read
```

This is very likely caused by this setting in Settings->Actions->General. It looks like even explicit write permission in job config is not enough and you need to change that setting.
Screenshot 2024-11-11 at 12 42 23

**Comment by KapJI** [comment]
It seems there is third option. `lock-thread` workflow shows that it's possible to set write permissions on workflow level.

**Pull request merged**
