### PR TITLE
Render docs with github.com/charmbracelet/glamour

### PR DESCRIPTION
**Pull request by twpayne**

### CODE REVIEW

**Comment by twpayne** [comment]
This needs a few fixes in glamour: https://github.com/charmbracelet/glamour/issues/42, https://github.com/charmbracelet/glamour/issues/44, and https://github.com/charmbracelet/glamour/issues/4.

**Comment by muesli** [comment]
@twpayne If it helps reducing the amount of maintainable code for you, I'd be happy to adjust `glamour`'s `simple` style to match `chezmoi`'s current style settings.

**Comment by twpayne** [comment]
@muesli Thank you very much for this kind offer! I've opened https://github.com/charmbracelet/glamour/issues/50 to discuss a change to glamour which would help a lot.

**Comment by twpayne** [comment]
@muesli thanks very much for merging https://github.com/charmbracelet/glamour/pull/55, chezmoi now uses `glamour`'s `ascii` style (#547).

**Pull request merged**
