### PR TITLE
fix: Return unparsed gopass output in gopassRaw template func

### PR DESCRIPTION
**Pull request by twpayne**
Refs #1635.

### CODE REVIEW

**Comment by twpayne** [comment]
cc @davidolrik

**Review by davidolrik — CHANGES_REQUESTED** [review]
You should remove the `--password` flag as that only returns the first line.

**Review by davidolrik — APPROVED** [review]
Functionality looks good!

**Comment by twpayne** [comment]
Thanks for the review :)

**Comment by davidolrik** [comment]
Thanks for the quick fix!

**Pull request merged**
