### PR TITLE
Fix spelling errors in FAQ

### PR DESCRIPTION
**Pull request by thernstig**

### CODE REVIEW

**Comment by thernstig** [comment]
Time to give back some to the project.

I've followed CONTRIBUTING.md but still got an error when running `go generate`. I am not an avid go user, so unsure what the problem is, as seen below. It did still seem to modify multiple files, so I hope everything is correct. Feel free to download + push if I failed somehow with the doc generation.

```sh
go: github.com/spf13/viper upgrade => v1.7.0
go: github.com/coreos/go-semver upgrade => v0.3.0
go: github.com/magiconair/properties upgrade => v1.8.1
# github.com/charmbracelet/glamour/ansi
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/codeblock.go:110:3: unknown field 'Forward' in struct literal of type indent.Writer
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/heading.go:70:3: unknown field 'Forward' in struct literal of type indent.Writer
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/margin.go:37:3: unknown field 'Forward' in struct literal of type padding.Writer
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/margin.go:51:3: unknown field 'Forward' in struct literal of type indent.Writer
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/table.go:51:3: unknown field 'Forward' in struct literal of type indent.Writer
~/code/chezmoi (faq) [2]> go generate
# github.com/charmbracelet/glamour/ansi
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/codeblock.go:110:3: unknown field 'Forward' in struct literal of type indent.Writer
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/heading.go:70:3: unknown field 'Forward' in struct literal of type indent.Writer
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/margin.go:37:3: unknown field 'Forward' in struct literal of type padding.Writer
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/margin.go:51:3: unknown field 'Forward' in struct literal of type indent.Writer
../../go/pkg/mod/github.com/charmbracelet/glamour@v0.1.0/ansi/table.go:51:3: unknown field 'Forward' in struct literal of type indent.Writer
main.go:3: running "go": exit status 2
~/code/chezmoi (faq) [1]>
```

**Comment by twpayne** [comment]
Thanks for this! The build failure is due to a dependency not having quite the right Go modules setup. Could you re-push the commit without the changes to `go.{mod,sum}`?

**Comment by thernstig** [comment]
Ok, will do. Please see my previous comment on failres I received. Oh, I am using WSL1, so that might be the problem. Will go for WSL2 as soon as I receive the new Win 10 2004 build where I can install it instead, that might solve future problems like this (just guessing).

**Comment by twpayne** [comment]
Thank you :)

**Pull request merged**
