### PR TITLE
feat: Add --interactive flag

### LINKED ISSUE #2245: Add a flag to chezmoi apply to always show a prompt when chezmoi going to make changes to destination state
## Is your feature request related to a problem? Please describe.

When running `chezmoi apply` chezmoi shows the prompt i.e`has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]?` only if the destination state is diverted from the source state.
If the changes are in the source state. When running `chezmoi apply` chezmoi directly applies the change and shows diff if `-v` flag is used.

When managing a single file via external e.g plugins for zsh or mpv, `chezmoi apply` will apply the changes without the prompt.
Sometimes you don't want to upgrade these plugins. A prompt will be helpful to quickly diff or skip the change.

## Describe the solution you'd like

If possible a flag can be added to `chezmoi apply` which will always show a prompt when chezmoi going to make changes to destination state. It will cover the external case and will make `chezmoi apply` more controllable.

## Describe alternatives you've considered

Run `chezmoi diff` before `chezmoi apply` and exclude the file if you don't want to update.

## Additional context

None

### PR DESCRIPTION
**Pull request by twpayne**
Fixes #2245.

With this you can do:

```console
$ chezmoi apply --interactive
```

and you'll be prompted for each changed entry.

@sm1999 is this what you had in mind? Would you be able to test this?

### CODE REVIEW

**Comment by sm1999** [comment]
Yes. I tested it locally and it works as expected.
Liked the new prompt. I sometimes pressed `a` accidentally on the old prompt thinking `a` for accept.
Thank you so much!

**Comment by twpayne** [comment]
Great! Thank you for the testing :)

**Comment by sm1999** [comment]
@twpayne in the new prompt pressing a for apply changes to all files only change the current file for which prompt is shown and fallback to the old prompt.
If I understand correctly `c.force = true` is missing.
Following diff fixes it.
```
diff --git a/pkg/cmd/config.go b/pkg/cmd/config.go
index 2b9b72e7..6dc19f2e 100644
--- a/pkg/cmd/config.go
+++ b/pkg/cmd/config.go
@@ -881,6 +881,7 @@ func (c *Config) defaultPreApplyFunc(
 				return chezmoi.Skip
 			case choice == "all":
 				c.interactive = false
+                c.force = true
 				return nil
 			case choice == "quit":
 				return chezmoi.ExitCodeError(0)

```

**Comment by sm1999** [comment]
@twpayne ping

**Comment by twpayne** [comment]
@sm1999 Why are you pinging me?

**Comment by sm1999** [comment]
I was uncertain that you saw my comment above.
Basically what is happening is pressing a for all fallbacks to the old prompt for the remaining changed files. 
```
❯ chezmoi apply -n
Apply .config/git/config [diff,yes,no,all,quit]? a
.config/htop/htoprc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]?
```
Is it intentional?

**Comment by twpayne** [comment]
Yes, this is intentional. There are two conditions here:
1. Do you want to be prompted for every target that chezmoi might change? (`--interactive`)
2. Do you want to overwrite changes made by other programs? (`--force`)

It's deliberate to keep the two separate.

**Comment by sm1999** [comment]
Thanks for the explanation!

**Pull request merged**
