### PR TITLE
chezmoi2: Restore secret keyring command

### PR DESCRIPTION
**Pull request by twpayne**
Refs #987.

As [reported by](https://github.com/twpayne/chezmoi/issues/987#issuecomment-761884922) @zb140.

> Is the `chezmoi secret` subcommand permanently gone?

No :) I just didn't realize that it was actively used. This PR restores it for `secret keyring`. For other password managers, I think that the password manager's CLI should be a better option than using `chezmoi secret` but let's see what users report.

> I've been using it as part of my secret caching scheme to work around the perf issues in 1password. Specifically, I'm caching secrets in keepass and storing the keepass db password in the OS keyring (which gets unlocked when I sign into the computer). Then I use a shell alias to do `chezmoi secret keyring get --service secret_cache_pw --user zb | chezmoi apply` to apply dotfile changes. I'm sure I can find a workaround if needed.

This PR should fix this, but there's a deeper issue here that this PR doesn't address. chezmoi2 tries to read passwords from a TTY, and will get one if necessary. It so happens that I don't know how to do this on Windows yet (see https://github.com/twpayne/chezmoi/blob/master/chezmoi2/cmd/config.go#L634-L651) so on Windows chezmoi2 will happily read a password from stdin. The long term fix is probably to (a) read passwords from a TTY on Windows and (b) add a flag to allow passwords to be read from stdin if needed.

@zb140 would you mind testing this PR? Please do merge it or push fixes to this branch if needed.

### CODE REVIEW

**Comment by zb140** [comment]
I added the `--service` and `--user` args back in, and it's working great now.  @twpayne I couldn't find another example of required args in chezmoi2.  Is this (https://github.com/twpayne/chezmoi/blob/secret-keyring/chezmoi2/cmd/secretkeyringcmd.go#L27) an appropriate pattern?  I pretty much just copied it from chezmoi1, except that `panicIfError` doesn't exist anymore.

**Comment by twpayne** [comment]
That's great, thanks! I'll add a helper for catching errors from `MarkPersistentFlagRequired` in a separate PR as it's a common pattern.

**Comment by zb140** [comment]
@twpayne Excellent!

For the TTY stuff, console apps on Windows can be... complicated :smile:  (Come to think of it, so many parts of the system are called "console" that it's kind of complicated to even _talk_ about...)  When a console app is launched, the OS will create a console handle (if the app didn't inherit one from the command line that launched it) and connect it to stdin.  The app is then free to call Console APIs if it wants.

If the primary goal is just to enforce that prompts should only go to a real terminal (unless overridden by the new flag you mentioned), then I think it should be sufficient to make `getTTY` do something like this:
```go
if runtime.GOOS == "windows" {
	if stdin, ok := c.stdin.(*os.File); !ok || !term.IsTerminal(int(stdin.Fd())) {
		return nil, nil, fmt.Errorf("can't read from non-terminal")
	}
	c.ttyReader = bufio.NewReader(c.stdin)
	c.ttyWriter = c.stdout
}
```
`term.IsTerminal` does return the correct result using the Windows Console APIs.

If it's more complicated than that, then it will probably be necessary to go directly to the Console APIs.  Let's cross that bridge if we come to it :smile:

**Comment by twpayne** [comment]
Thanks for all the info on the terminal stuff. https://github.com/twpayne/chezmoi/pull/990/commits/0887458a637be1d10e0c85aa028e168b473e938f should fix it. It uses `golang.org/x/term` which (fingers crossed) also includes Windows terminal support. With this change, chezmoi2 will try to read input from a terminal by default. If you want to read from stdin (as in your `chezmoi secret keyring get | chezmoi apply` case) then you'll need to pass the `--no-tty` flag to `chezmoi apply`.

**Comment by zb140** [comment]
Yep, that mostly works.  I tried both the terminal and `--no-tty` variants and was able to enter the password and have it work.

The one issue I encountered was that my computer doesn't actually print the prompt ("Insert password to unlock...") even though it does listen for and accept input.  After some tracing through the `x/term` code, I eventually tracked it down to `x/term`'s call to `Write` on the terminal's `ReadWriter` was just not doing anything.  I replaced the stdin file with a `ReadWriter` composite of stdin and stdout (like this: https://github.com/zb140/chezmoi/commit/4f14e882044a755a5bf98bc2582e9313cf59119b) and I get a working prompt and working input.  I also ran all the tests and they passed.  But there still may be some other consequence of the change I haven't thought of yet.

Side note: I have a hunch that this behavior of the prompt not working might actually be machine-dependent rather than simply a blanket "it doesn't work on Windows".  I didn't have time to pull on that thread tonight but I should be able to do some digging tomorrow.

**Comment by twpayne** [comment]
https://github.com/zb140/chezmoi/commit/4f14e882044a755a5bf98bc2582e9313cf59119b looks good to me - I was going to suggest the same.

**Pull request merged**
