### PR TITLE
chore: Split test-ubuntu job by umask

### PR DESCRIPTION
**Pull request by KapJI**
This is the slowest job now, get final signal 6 minutes earlier.

### CODE REVIEW

**Comment by KapJI** [comment]
These CI jobs are slower than expected because `test-release` cache was not ready yet in master.
And old `setup-go-Linux-x64-ubuntu22-go-1.23.3-5ad9291462e95d786177aba5b070c841d314c4fffb19674ef230e34a62babdcf` (size 130 MB) cache entry was created for website and doesn't contain all required inputs.

@twpayne can you please remove it manually on https://github.com/twpayne/chezmoi/actions/caches ?

**Comment by twpayne** [comment]
Thank you again :)

**Comment by KapJI** [comment]
Whole workflow finished in under 9 minutes: https://github.com/twpayne/chezmoi/actions/runs/11745949355
Nice progress from 20+ minutes before.

I think #3366 can be closed now.

To make it even faster, tests need to be split into multiple parallel jobs. I just found this action which allows to do that pretty easily: https://github.com/hashicorp-forge/go-test-split-action

Are you interested to try it? I think just 2 slices should be enough.

**Comment by twpayne** [comment]
> I think #3366 can be closed now.

Agreed! Thank you so much for this extremely impressive performance improvement!



> To make it even faster, tests need to be split into multiple parallel jobs. I just found this action which allows to do that pretty easily: https://github.com/hashicorp-forge/go-test-split-action
> 
> Are you interested to try it? I think just 2 slices should be enough.

I'm not sure it'll help too much for chezmoi because the test duration is totally dominate by the `./internal/cmd` package and all its testscript tests. Here's a run on my dev machine:

```console
$ go test ./... -count=1
?       github.com/twpayne/chezmoi/v2/assets/chezmoi.io/docs    [no test files]
?       github.com/twpayne/chezmoi/v2/assets/scripts    [no test files]
?       github.com/twpayne/chezmoi/v2/assets/templates  [no test files]
?       github.com/twpayne/chezmoi/v2/internal/chezmoiassert    [no test files]
?       github.com/twpayne/chezmoi/v2/internal/chezmoierrors    [no test files]
?       github.com/twpayne/chezmoi/v2/internal/chezmoimaps      [no test files]
?       github.com/twpayne/chezmoi/v2/internal/chezmoiset       [no test files]
ok      github.com/twpayne/chezmoi/v2   0.040s
ok      github.com/twpayne/chezmoi/v2/assets/chezmoi.io/docs/reference/commands 0.002s
ok      github.com/twpayne/chezmoi/v2/internal/archivetest      0.006s
?       github.com/twpayne/chezmoi/v2/internal/cmds/execute-template    [no test files]
?       github.com/twpayne/chezmoi/v2/internal/cmds/lint-txtar  [no test files]
ok      github.com/twpayne/chezmoi/v2/internal/chezmoi  3.832s
ok      github.com/twpayne/chezmoi/v2/internal/chezmoibubbles   0.007s
ok      github.com/twpayne/chezmoi/v2/internal/chezmoigit       0.003s
ok      github.com/twpayne/chezmoi/v2/internal/chezmoilog       0.003s [no tests to run]
ok      github.com/twpayne/chezmoi/v2/internal/chezmoitest      0.004s
ok      github.com/twpayne/chezmoi/v2/internal/cmd      15.729s
ok      github.com/twpayne/chezmoi/v2/internal/cmds/generate-install.sh 0.004s
ok      github.com/twpayne/chezmoi/v2/internal/cmds/lint-commit-messages        0.002s
ok      github.com/twpayne/chezmoi/v2/internal/cmds/lint-whitespace     0.002s
```

So, sharding packages across multiple jobs won't help significantly until the `./internal/cmd` tests are themselves split into multiple packages.

**Pull request merged**
