### PR TITLE
feat: Skip the purge of source if not created by chezmoi

### PR DESCRIPTION
**Pull request by felipecrs**
Closes https://github.com/twpayne/chezmoi/issues/1723

### CODE REVIEW

**Comment by felipecrs** [comment]
@twpayne I created this PR just to illustrate what I had in mind. It's not yet ready because it at least is missing tests.

But I will totally understand if you do not agree, as you mentioned earlier in https://github.com/twpayne/chezmoi/issues/1723.

**Comment by twpayne** [comment]
Thanks for your work here.

To be clear about the intention of the existing commands:
A. `chezmoi init` means "start using chezmoi for the first time by creating an empty source directory and local repo" or (sadly, overloaded, as already stated) "re-generate chezmoi's config file".
B. `chezmoi init --one-shot $REPO` means "install dotfiles from `$REPO`, and then remove all traces of chezmoi".
C. `chezmoi purge` means "remove all traces of chezmoi from the system".

As it stands, there are a few problems with this PR:
1. As can been seen from the failing tests, this breaks the `chezmoi purge` command, breaking intention C above.
2. It seems to prevent `chezmoi init --purge` from removing the source directory in the specific case of `chezmoi init` being called with no positional arguments, i.e intention A above, when `chezmoi init` calls `git init` to create a new git repo in the source directory if no such git repo already exists. This is different to the described intention in #1723 which only refers to the source directory, not the git repo within it. `chezmoi init --purge` also makes no sense: it means "initialize chezmoi for the first time, and then remove all traces of it".
3. I think the original intention of #1723 was to prevent `chezmoi init --one-shot $REPO` from deleting the source directory in the case that it already existed, but we see that this is contrary to intention B.

Happy to hear clarifications.

**Comment by felipecrs** [comment]
1. This is not intended. I will fix it. Thanks for noting.
2. You are right. I see no clear way around this. But as you mentioned, there are no use-cases for `chezmoi init --purge`. Perhaps this compromise of "breaking" such usage can be taken?
3. No. It's not `chezmoi init --one-shot $REPO` but `chezmoi init --one-shot --source /my-repo`, which have no positional arguments. However, if I change to be effective on just `--one-shot` we will run into 2. again (but with `chezmoi init --one-shot` as opposed to `chezmoi init --purge`).

**Comment by felipecrs** [comment]
Or, I can change the documentation to say that chezmoi will _attempt_ to delete the _sourceDir_. In my case, it will then fail because my file system is readonly, but chezmoi won't exit with an error because it was just an attempt.

**Comment by twpayne** [comment]
Given that the desired functionality can be achieved using existing `chezmoi` commands I will close this.

**Pull request closed without merging**
