### PR TITLE
chore: Update Makefile

### PR DESCRIPTION
**Pull request by MuXiu1997**

### CODE REVIEW

**Review by twpayne — COMMENTED** [review]
What does this change do and how does it work? From my reading of the GNU Make Reference Manual this change makes all targets in the Makefile not PHONY, which is undesirable.

**Comment by MuXiu1997** [comment]
@twpayne 
```diff
+ .PHONY: ;
+
```
it makes all targets in the Makefile PHONY
Just what we need

**Comment by twpayne** [comment]
> @twpayne
> 
> ```diff
> + .PHONY: ;
> +
> ```
> 
> it makes all targets in the Makefile PHONY Just what we need

Could you point to the part of the GNU Make Reference Manual that describes this behavior? I couldn't find it.

**Comment by MuXiu1997** [comment]
I was wrong, I learned this from elsewhere, but didn't verify that it would work
Indeed, it doesn't work, sorry

**Comment by MuXiu1997** [comment]
ref: https://github.com/photoprism/photoprism/blob/7940786ce95faa0692e1834ed9123e40a8cf62b7/Makefile#L1-L5

**Pull request closed without merging**
