### PR TITLE
Initial templating docs

### PR DESCRIPTION
**Pull request by fwSmit**
This is the documentation I've written so far. It's not yet finished, so you can decide to not put it in master yet.
I'm planning to do a lot more documentation, so let me know what you think of this.

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks for this, this is a great start!

Please note:
* After updating documentation you have to run `go generate`, as [described in the contributing guide](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#generated-code).
* "Templating" does not include an "e". Please can you run a spell checker.
* Please follow the Markdown style of the existing docs with respect to formatting, blank lines, etc.

If you don't want to do the above, I'll be happy to merge your PR as-is and make the changes after. The content that you're creating is more important that the nits I mention.

Thanks again for this!

**Comment by fwSmit** [comment]
Thank you for the comments! I will submit a new version soon with the improvements and some more content.

**Comment by fwSmit** [comment]
I've fixed the things you mentioned. Now I will write some more documentation. Feel free to merge the pr already if it's good.

**Comment by fwSmit** [comment]
Wait, don't merge yet, I have to fix some more formatting issues

**Comment by fwSmit** [comment]
It should be fine now

**Comment by twpayne** [comment]
Thank you for this, this is great! Would you mind squashing the commits into a single commit?

**Comment by fwSmit** [comment]
I have squashed it into one commit (with some help from the internet).

**Comment by twpayne** [comment]
Thank you very much - this is a great contribution. Please do keep adding more :)

**Comment by fwSmit** [comment]
Yes I will do that

**Pull request merged**
