### PR TITLE
Fix #393 Disable the default template auto generating

### LINKED ISSUE #393: Don't auto generate the template by default when adding files as templates
The current behavior of "adding files as templates" is quite annoying as it always modify the template although I just want to add it as it is. Should we disable the template auto generating by default and let users add a flag such as `--template-auto-generate` for it when they intend to do so?

### PR DESCRIPTION
**Pull request by 15cm**
Fix #393. Disable the default template auto generating, which can be enable by setting the
`--template-auto-generate` flag added by this commit.

### CODE REVIEW

**Comment by twpayne** [comment]
Thanks very much for the PR :)

Please can you do the following:

* Rename the flag to `--autotemplate`.
* Rename the field in `struct AddOptions` to `AutoTemplate`.
* Add the short flag `-a`.
* Run `make completions` to generate the shell completions and commit them.
* Update the autotemplate test that currently fails (set `AutoTemplate: true` in `AddOptions`.
* Add a test the ensures that autotemplate is off by default.

Let me know if more information is needed. Equally, if you don't have time to work on this, please tell me and I can build on your work here.

**Comment by 15cm** [comment]
No probelm. Will take your suggestions and work on it these days.

**Comment by 15cm** [comment]
I have got your suggestions done but met an issue with CI. Could you please take a look for at why the CI failed to find some files when testing in the vfs. Actually the CI seems to be fail on your last commit 8 days ago: https://ci.appveyor.com/project/twpayne/chezmoi/builds/25833560

**Comment by twpayne** [comment]
Thanks very much for making these changes. I think the Windows builds are flaky at the moment (#392) - the builds started failing after a documentation change. It is possible that I broke something somewhere else. I don't have a Windows machine to test on, so I can only use the AppVeyor CI to debug problems, which has a very slow feedback loop.

I won't have time to work on this for a couple of weeks due to other commitments, but I do plan to fix the Windows CI and get this PR merged.

**Comment by twpayne** [comment]
Following #403, could you rebase this PR on the latest `master`?

**Comment by 15cm** [comment]
Done. Thanks for your help.

**Comment by twpayne** [comment]
Thanks for updating the PR. It looks like you merged `master` rather than rebasing, and consequently the history is a little mixed up with multiple duplicate commits. I've squashed and rebased everything in #404.

Thanks again for the great contribution!

**Pull request closed without merging**
