### PR TITLE
fix: Fix dump command in the presence of config file templates

### LINKED ISSUE #2092: `chezmoi dump` crashes
## Describe the bug

After having read about `chezmoi dump` in the documentation I wanted to play around with it. However for me it just crashes:

```console
$ chezmoi dump            
chezmoi: warning: config file template has changed, run chezmoi init to regenerate config file
panic: update to no update system

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/pkg/chezmoi.noUpdateSystemMixin.RunCmd(...)
	/home/runner/work/chezmoi/chezmoi/pkg/chezmoi/system.go:84
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*TargetStateModifyDirWithCmd).Apply(0x1de21e0, {0xf782d0, 0x1f93df8}, {0xf76ff4, 0x1f93de0}, {0xf7495c, 0x1e28b88})
	/home/runner/work/chezmoi/chezmoi/pkg/chezmoi/targetstateentry.go:81 +0x104
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).Apply(0x1f72180, {0xf782d0, 0x1f93df8}, {0xf78460, 0x1f93de8}, {0xf76ff4, 0x1f93de0}, {{0x0, 0x0}}, {{0x1df44b0, ...}}, ...)
	/home/runner/work/chezmoi/chezmoi/pkg/chezmoi/sourcestate.go:681 +0xd5c
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).applyArgs(0x1e44000, {0xf757ac, 0x1c260e0}, {0xf782d0, 0x1f93df8}, {{0x0, 0x0}}, {0x15603c4, 0x0, 0x0}, ...)
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/config.go:619 +0x734
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).runDumpCmd(0x1e44000, 0x2266160, {0x15603c4, 0x0, 0x0})
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/dumpcmd.go:43 +0x118
github.com/spf13/cobra.(*Command).execute(0x2266160, {0x15603c4, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x6b0
github.com/spf13/cobra.(*Command).ExecuteC(0x1c24580)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x414
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).execute(0x1e44000, {0x1c0c048, 0x1, 0x1})
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/config.go:1120 +0x78
github.com/twpayne/chezmoi/v2/pkg/cmd.runMain({{0xf6f338, 0x6}, {0xf76bb8, 0x28}, {0xf72d78, 0x14}, {0xf708d8, 0xa}}, {0x1c0c048, 0x1, ...})
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/cmd.go:264 +0x148
github.com/twpayne/chezmoi/v2/pkg/cmd.Main({{0xf6f338, 0x6}, {0xf76bb8, 0x28}, {0xf72d78, 0x14}, {0xf708d8, 0xa}}, {0x1c0c048, 0x1, ...})
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/cmd.go:128 +0x38
main.main()
	/home/runner/work/chezmoi/chezmoi/main.go:26 +0xd8
```

**NOTE!** Only dump says "chezmoi: warning: config file template has changed, run chezmoi init to regenerate config file". Running `chezmoi init` does not remove this warning. So best as I can tell that line is a lie.

This happens both on my Pi (official binary build) and on my desktop (Arch Linux package).

## To reproduce

```console
$ chezmoi dump
```

## Expected behavior

Not crash?

## Output of command with the `--verbose` flag

Exactly the same:

```console
$ chezmoi dump --verbose
chezmoi: warning: config file template has changed, run chezmoi init to regenerate config file
panic: update to no update system

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/pkg/chezmoi.noUpdateSystemMixin.RunCmd(...)
	/home/runner/work/chezmoi/chezmoi/pkg/chezmoi/system.go:84
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*TargetStateModifyDirWithCmd).Apply(0x21e7c50, {0xf782d0, 0x2391e20}, {0xf76ff4, 0x2391e08}, {0xf7495c, 0x2331e30})
	/home/runner/work/chezmoi/chezmoi/pkg/chezmoi/targetstateentry.go:81 +0x104
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).Apply(0x2372180, {0xf782d0, 0x2391e20}, {0xf783fc, 0x238fb40}, {0xf76ff4, 0x2391e08}, {{0x0, 0x0}}, {{0x229ab10, ...}}, ...)
	/home/runner/work/chezmoi/chezmoi/pkg/chezmoi/sourcestate.go:681 +0xd5c
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).applyArgs(0x2248000, {0xf757ac, 0x20280e0}, {0xf782d0, 0x2391e20}, {{0x0, 0x0}}, {0x2390800, 0x0, 0x1}, ...)
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/config.go:619 +0x734
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).runDumpCmd(0x2248000, 0x267e000, {0x2390800, 0x0, 0x1})
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/dumpcmd.go:43 +0x118
github.com/spf13/cobra.(*Command).execute(0x267e000, {0x23907f8, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x6b0
github.com/spf13/cobra.(*Command).ExecuteC(0x2026580)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x414
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).execute(0x2248000, {0x2024020, 0x2, 0x2})
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/config.go:1120 +0x78
github.com/twpayne/chezmoi/v2/pkg/cmd.runMain({{0xf6f338, 0x6}, {0xf76bb8, 0x28}, {0xf72d78, 0x14}, {0xf708d8, 0xa}}, {0x2024020, 0x2, ...})
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/cmd.go:264 +0x148
github.com/twpayne/chezmoi/v2/pkg/cmd.Main({{0xf6f338, 0x6}, {0xf76bb8, 0x28}, {0xf72d78, 0x14}, {0xf708d8, 0xa}}, {0x2024020, 0x2, ...})
	/home/runner/work/chezmoi/chezmoi/pkg/cmd/cmd.go:128 +0x38
main.main()
	/home/runner/work/chezmoi/chezmoi/main.go:26 +0xd8
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.17.0, commit 7c70bff83d7c1dbe9ed3be486e3a6023e05c5426, built at 2022-05-26T00:05:04Z, built by goreleaser
ok        latest-version       v2.17.0
ok        os-arch              linux/arm (Raspbian GNU/Linux 11 (bullseye))
ok        uname                Linux cerberus 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
ok        go-version           go1.18.2 (gc)
ok        executable           ~/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.yaml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found /usr/bin/zsh
ok        shell-args           /usr/bin/zsh
ok        cd-command           found /usr/bin/zsh
ok        cd-args              /usr/bin/zsh
ok        edit-command         found /bin/nano
ok        edit-args            /bin/nano
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.30.2
warning   merge-command        bcompare not found in $PATH
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.27
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

Presumably it is something in my dotfiles repo that triggers this. I have not made this public and is reluctant to do so as well. If you need I can try to "bisect" my chezmoi directory and try to find a small reproducer.

### PR DESCRIPTION
**Pull request by twpayne**
Refs #2092.

@VorpalBlade I'm reasonably sure that this fixes the problem you reported. Are you able to test this to confirm?

### CODE REVIEW

**Comment by VorpalBlade** [comment]
@twpayne I can try. Never built go code before.

**Comment by VorpalBlade** [comment]
As far as I can tell, no dice. It does fix the warning at the start though.

```
❯ ./chezmoi dump
panic: update to no update system

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/pkg/chezmoi.noUpdateSystemMixin.RunCmd(...)
        /home/arvid/src/chezmoi/pkg/chezmoi/system.go:84
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*TargetStateModifyDirWithCmd).Apply(0xc00085a8a0, {0x131f920, 0xc000010048}, {0x131e008, 0xc0006e0420}, {0x1319c68?, 0xc00060ff40})
        /home/arvid/src/chezmoi/pkg/chezmoi/targetstateentry.go:81 +0x129
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).Apply(0xc00013a160, {0x131f920, 0xc000010048}, {0x131fc20, 0xc00027a000}, {0x131e008, 0xc0006e0420}, {{0x0?, 0x6?}}, {{0xc0004b9c80, ...}}, ...)
        /home/arvid/src/chezmoi/pkg/chezmoi/sourcestate.go:681 +0xbb2
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).applyArgs(0xc00057b500, {0x131b458, 0xc000036170}, {0x131f920, 0xc000010048}, {{0x0?, 0xc0005a8000?}}, {0x19f6e80, 0x0, 0x0}, ...)
        /home/arvid/src/chezmoi/pkg/cmd/config.go:619 +0x846
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).runDumpCmd(0xc00057b500, 0xc0000c1400, {0x19f6e80, 0x0, 0x0})
        /home/arvid/src/chezmoi/pkg/cmd/dumpcmd.go:43 +0x1ac
github.com/spf13/cobra.(*Command).execute(0xc0000c1400, {0x19f6e80, 0x0, 0x0})
        /home/arvid/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00036ac80)
        /home/arvid/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/arvid/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).execute(0xc00079fdf8?, {0xc000032050, 0x1, 0x1})
        /home/arvid/src/chezmoi/pkg/cmd/config.go:1120 +0x78
github.com/twpayne/chezmoi/v2/pkg/cmd.runMain({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, {0xc000032050, 0x1, ...})
        /home/arvid/src/chezmoi/pkg/cmd/cmd.go:264 +0x1b4
github.com/twpayne/chezmoi/v2/pkg/cmd.Main({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, {0xc000032050, 0x1, ...})
        /home/arvid/src/chezmoi/pkg/cmd/cmd.go:128 +0xb1
main.main()
        /home/arvid/src/chezmoi/main.go:26 +0x110
```

And new doctor if you care:

<details>

```
❯ ./chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              dev
warning   latest-version       v2.17.0
ok        os-arch              linux/amd64 (Arch Linux)
ok        uname                Linux theseus 5.18.0-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 May 2022 22:00:36 +0000 x86_64 GNU/Linux
ok        go-version           go1.18.2 (gc)
ok        executable           ~/src/chezmoi/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.yaml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
ok        edit-command         found /usr/bin/code
ok        edit-args            code -w
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.36.1
ok        merge-command        found /usr/bin/bcompare
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.35
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
ok        keepassxc-command    found /usr/bin/keepassxc-cli, version 2.7.1
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

**Comment by VorpalBlade** [comment]
Also interesting perhaps: If I have a modify_ script that fails (due to having a pyenv active), that happened before the crash and chezmoi exited instead of crashing

**Comment by VorpalBlade** [comment]
Also, dumping some specific files work, e.g. `./chezmoi dump ~/.zshrc`. This works with the released version too (albeit the warning displayed).

**Comment by twpayne** [comment]
> @twpayne I can try. Never built go code before.

Instructions are [here](https://www.chezmoi.io/install/#install-from-source).



> Also interesting perhaps: If I have a modify_ script that fails (due to having a pyenv active), that happened before the crash and chezmoi exited instead of crashing

This makes sense (to me, at least). chezmoi first generates the target state, and then `chezmoi dump` dumps it in JSON/YAML format. If a `modify_` script fails then the target state generation fails before `chezmoi dump` can print the output.

**Comment by VorpalBlade** [comment]
By exeperimenting with dumping on sub paths I found that it fails on something that is a chezmoi-external.

```console
cat .chezmoiexternal.toml     
[".local/own/vorpal-zsh-completions"]
    type = "git-repo"
    url = "https://github.com/VorpalBlade/vorpal-zsh-completions.git"
    refreshPeriod = "24h"
```
it crashes on ~/.local, ~/.local/own etc

Note! I don't know yet that this is the only thing it crashes on

**Comment by twpayne** [comment]
Thank you for the thorough testing and your zsh code to find the problem is very neat :)

I'll open a new PR to fix the external git repo / dump panic, and will merge this one now.

**Pull request merged**
