### PR TITLE
feat: Implement the path-style flag for status

### PR DESCRIPTION
**Pull request by Lattay**
Implementing proposed feature in #3242.

I moved the `pathstyle.go` file from `internal/cmd/` to `internal/chezmoi` to share the structure between `managed` and `status` and make that public to use in configuration.

Currently, `source-absolute` and `source-relative` are not implemented because I didn't see an obvious way to do it without refactoring, but I may very well be missing something as I am not yet familiar with the codebase.
Yet, does it make sense to implement these? I don't immediately see a use case for that, but I am not convinced it does not exist either.

What do you think?

### CODE REVIEW

**Comment by twpayne** [comment]
This looks excellent, thank you.

Please add some tests. I would add them to [this file](https://github.com/twpayne/chezmoi/blob/b0862194919262e73bbf8d9b54ac561a33d65720/internal/cmd/testdata/scripts/status.txtar) using [this file](https://github.com/twpayne/chezmoi/blob/b0862194919262e73bbf8d9b54ac561a33d65720/internal/cmd/testdata/scripts/managed.txtar#L63-L73) as a reference.

Note that paths on Windows are a nightmare, so don't spend time trying to get the tests to pass on Windows, especially if you don't have access to a Windows machine to test on.

**Comment by Lattay** [comment]
So it's my first time working with this test framework and I am very confused right now.
Here is my test failing:
```
            > [unix] cmp stdout golden/status-absolute
            diff stdout golden/status-absolute
            --- stdout
            +++ golden/status-absolute
            @@ -1,12 +1,12 @@
            - A $WORK/home/user/.create
            - A $WORK/home/user/.dir
            - A $WORK/home/user/.dir/file
            - A $WORK/home/user/.dir/subdir
            - A $WORK/home/user/.dir/subdir/file
            - A $WORK/home/user/.empty
            - A $WORK/home/user/.executable
            - A $WORK/home/user/.file
            - A $WORK/home/user/.private
            - A $WORK/home/user/.readonly
            - A $WORK/home/user/.symlink
            - A $WORK/home/user/.template
            + A $WORK/home/user/.create
            + A $WORK/home/user/.dir
            + A $WORK/home/user/.dir/file
            + A $WORK/home/user/.dir/subdir
            + A $WORK/home/user/.dir/subdir/file
            + A $WORK/home/user/.empty
            + A $WORK/home/user/.executable
            + A $WORK/home/user/.file
            + A $WORK/home/user/.private
            + A $WORK/home/user/.readonly
            + A $WORK/home/user/.symlink
            + A $WORK/home/user/.template
```

The problem is as far as I can tell there is no difference, so... What am I doing wrong?
I committed the test so that you can have a look. It is so simple I expected it to work first try, but here I am.

**Comment by bradenhilton** [comment]
I don't think testscript resolves environment variables inside golden files. They are supposed to be static text.

```console
❯ go test ./internal/cmd/... -run=TestScript/^status$
--- FAIL: TestScript (0.00s)
    --- FAIL: TestScript/status (0.33s)
        testscript.go:534: # FIXME add more tests (0.016s)
            # test that chezmoi status lists all files to be added (0.212s)
            # test that the --path-style=absolute works as expected (0.078s)
            > exec chezmoi status --path-style=absolute
            [stdout]
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.create
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.dir
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.dir/file
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.dir/subdir
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.dir/subdir/file
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.empty
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.executable
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.file
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.private
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.readonly
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.symlink
             A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.template
            > cmp stdout golden/status-absolute
            diff stdout golden/status-absolute
            --- stdout
            +++ golden/status-absolute
            @@ -1,12 +1,12 @@
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.create
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.dir
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.dir/file
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.dir/subdir
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.dir/subdir/file
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.empty
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.executable
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.file
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.private
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.readonly
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.symlink
            - A C:/Users/User/AppData/Local/Temp/go-test-script3156411014/script-status/home/user/.template
            + A $WORK/home/user/.create
            + A $WORK/home/user/.dir
            + A $WORK/home/user/.dir/file
            + A $WORK/home/user/.dir/subdir
            + A $WORK/home/user/.dir/subdir/file
            + A $WORK/home/user/.empty
            + A $WORK/home/user/.executable
            + A $WORK/home/user/.file
            + A $WORK/home/user/.private
            + A $WORK/home/user/.readonly
            + A $WORK/home/user/.symlink
            + A $WORK/home/user/.template

            FAIL: testdata\scripts\status.txtar:12: stdout and golden/status-absolute differ

FAIL
FAIL    github.com/twpayne/chezmoi/v2/internal/cmd      0.501s
FAIL
```

**Comment by twpayne** [comment]
> I don't think testscript resolves environment variables inside golden files.

That's right. You need to use `cmpenv` instead of `cmp` for that, i.e.

    [unix] cmpenv stdout golden/status-absolute

**Comment by bradenhilton** [comment]
> That's right. You need to use `cmpenv` instead of `cmp` for that, i.e.
> 
> ```
> [unix] cmpenv stdout golden/status-absolute
> ```

I was sure I could remember us running into this before and then I realized it was in https://github.com/twpayne/chezmoi/pull/3204#issuecomment-1697504286.

**Comment by Lattay** [comment]
Oh, ok, I get it. Fixing that right now.

Should I also test the config option btw?
I think it is a good idea, but I am not sure how to do it.
I have seen some tests with appendline which seems a good start, but I am not sure what should be done before that for the config file to exist and what should be done after to avoid polluting other tests.

**Comment by bradenhilton** [comment]
@Lattay You can try creating a new home with its own config. See https://github.com/twpayne/chezmoi/blob/b0862194919262e73bbf8d9b54ac561a33d65720/internal/cmd/testdata/scripts/secret.txtar#L12-L36 for an example.

**Comment by Lattay** [comment]
@bradenhilton cool, thanks, I got it working with your suggestion!

So I think the feature is done now. Tell me if it lacks anything.

**Comment by bradenhilton** [comment]
I think you can do the config test last (between `# test that chezmoi status does not emit status for equivalent modifications` and `-- golden/status --`) to remove the need to `chhome` back.

The linter is complaining that the files are not in order, I think you need to move the `-- home2/user/.config/chezmoi/chezmoi.toml --` file to the bottom to resolve this.

**Comment by twpayne** [comment]
> The linter is complaining that the files are not in order, I think you need to move the -- home2/user/.config/chezmoi/chezmoi.toml -- file to the bottom to resolve this.

You can also run `make format` to resolve this.

**Comment by twpayne** [comment]
Thank you, this is perfect.

Please run `make format` to fix the file order in the test, squash everything into a single commit, and it's good to merge :)

**Comment by Lattay** [comment]
Here we are, formatted, linted, tested :+1: thanks for the help!

**Comment by Lattay** [comment]
Ok, all done now !

**Pull request merged**
