### PR TITLE
fix: fix error when determining GOARCH in install.ps1

### PR DESCRIPTION
**Pull request by bradenhilton**
Fixes https://github.com/twpayne/chezmoi/issues/3749.

### CODE REVIEW

**Comment by bradenhilton** [comment]
@twpayne It would be useful to test the script with both `pwsh` and `powershell`. I am considering refactoring this PR to only include the change in https://github.com/twpayne/chezmoi/pull/3751/commits/593dc291b2100c745d5b119525be5d796eb351f9 and merging.

**Comment by bradenhilton** [comment]
```console
❯ docker run -it mcr.microsoft.com/windows:ltsc2019
Microsoft Windows [Version 10.0.17763.5696]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> iex "&{$(irm 'https://raw.githubusercontent.com/twpayne/chezmoi/e269c0ce3d2b2bb8263122930747d8df0e968cf9/assets/
scripts/install.ps1')} -d"
DEBUG: BinDir: C:\bin
DEBUG: Tag: latest
DEBUG: ChezmoiArgs:
DEBUG: tempDir: C:\Users\ContainerAdministrator\AppData\Local\Temp\c01668df-6c72-4392-aaea-396a2ed3fecf
DEBUG: goOS: windows
DEBUG: goArch: amd64
DEBUG: checking GitHub for tag latest
DEBUG: found tag v2.48.1 for latest
found version 2.48.1 for latest/windows/amd64
DEBUG: binarySuffix: .exe
DEBUG: archiveFormat: zip
DEBUG: goOSExtra:
DEBUG: archiveFilename: chezmoi_2.48.1_windows_amd64.zip
DEBUG: tempArchivePath:
C:\Users\ContainerAdministrator\AppData\Local\Temp\c01668df-6c72-4392-aaea-396a2ed3fecf\chezmoi_2.48.1_windows_amd64.zi
p
DEBUG: downloading https://github.com/twpayne/chezmoi/releases/download/v2.48.1/chezmoi_2.48.1_windows_amd64.zip
DEBUG: downloading https://github.com/twpayne/chezmoi/releases/download/v2.48.1/chezmoi_2.48.1_checksums.txt as string
DEBUG: extracting
C:\Users\ContainerAdministrator\AppData\Local\Temp\c01668df-6c72-4392-aaea-396a2ed3fecf\chezmoi_2.48.1_windows_amd64.zi
p to C:\Users\ContainerAdministrator\AppData\Local\Temp\c01668df-6c72-4392-aaea-396a2ed3fecf
DEBUG: binaryFilename: chezmoi.exe
DEBUG: tempBinaryPath:
C:\Users\ContainerAdministrator\AppData\Local\Temp\c01668df-6c72-4392-aaea-396a2ed3fecf\chezmoi.exe
DEBUG: binary: C:\bin\chezmoi.exe
installed C:\bin\chezmoi.exe
DEBUG: removing C:\Users\ContainerAdministrator\AppData\Local\Temp\c01668df-6c72-4392-aaea-396a2ed3fecf
```

**Comment by twpayne** [comment]
Gentle ping on this. I think you're waiting for action from me to merge this, but I'm not sure what that action is :)

**Comment by bradenhilton** [comment]
I forgot about this.

I was actually hoping you or @pmolodo could test it, as I still can only reproduce the issue in a Docker container, but it's just dawned on me that I forgot to actually ask for it to be tested.

The old code tries the cross-platform solutions first, which we have since discovered can throw an error on some versions of PowerShell and/or Windows. It assumes that, if the cross-platform solutions fail, the script must be running under Windows PowerShell.

The new code adds a check for the `Desktop` version of PowerShell (Windows PowerShell), which is not cross-platform, so it should be reasonably safe to assume that the script is being ran on a Windows machine.

**Pull request merged**
